managarm/managarm

posix/subsystem/src/file.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/process.cpp, posix/subsystem/src/process.hpp, protocols/posix/posix.proto
This PR implements get and set for user-id and related friends.
So far, the following has been implemented in at least a basic form
- `getuid()`
- `setuid()`, needs more work, as we do not check against effective user-id and friends. This should now be fixed and more POSIX compliant
- `geteuid()`
- `seteuid()`
- `getgid()`
- `setgid()`, doesn't exactly match linux in behaviour, probably `setgid` bit or `CAP_SETGID` capability.
- `getegid()`
- `setegid()`, doesn't exactly match linux in behaviour, probably `setgid` bit or `CAP_SETGID` capability.
=> posix: Implement get/set uid/euid/gid/egid

drivers/libblockfs/src/ext2fs.cpp, drivers/libblockfs/src/ext2fs.hpp, drivers/libblockfs/src/libblockfs.cpp, kernel/thor/meson.build, posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/tmp_fs.cpp, protocols/fs/fs.proto, protocols/fs/include/protocols/fs/server.hpp, protocols/fs/src/server.cpp, protocols/posix/posix.proto
This PR implements a `FCHMODAT` request in posix, allowing the libc functions `chmod()`, `fchmod()` and `fchmodat()` to function.
=> Implemented chmod

posix/subsystem/src/extern_socket.cpp, servers/netserver/meson.build, servers/netserver/src/ip/ip4.cpp, servers/netserver/src/ip/ip4.hpp, servers/netserver/src/ip/tcp4.cpp, servers/netserver/src/ip/tcp4.hpp
Missing features:
* FIN and RST.
* Listening (= server-side sockets).
* Propagation of errors through `sendMsg` and `recvMsg`.
* Retransmission.
* Path MTU discovery.
* Sophisticated congestion control.
This PR is based on an outdated version of #163. Before this PR is merged, #163 needs to be merged and this PR needs to be rebased.
**Only review the TCP commit, the remainder is reviewed in #163.**
=> servers/netserver: Add initial TCP implementation

posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/main.cpp, protocols/fs/fs.proto, protocols/fs/src/server.cpp, protocols/posix/posix.proto
We should return ILLEGAL_ARGUMENTS when flags is more then the two specified, not when either of those is declared.
=> posix: Fix a bug and implement RMDIR

drivers/libblockfs/src/ext2fs.cpp, drivers/libblockfs/src/ext2fs.hpp, drivers/libblockfs/src/libblockfs.cpp, posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/tmp_fs.cpp, protocols/fs/fs.proto, protocols/fs/include/protocols/fs/server.hpp, protocols/fs/src/server.cpp, protocols/posix/posix.proto
This PR implements the file system operation `utimensat` for `ext2fs` and `tmpfs`, adds an `chmod` file system operation for `tmpfs` and updates the access times on open for files on a `ext2` file system.
This PR is blocked on inclusion of managarm/mlibc#100
=> posix: Implement utimensat

docs/src/SUMMARY.md, docs/src/building.md, docs/src/contributing/contributing.md, docs/src/design/bragi/index.md, docs/src/design/frigg/index.md, docs/src/design/hel/index.md, docs/src/design/libasync/index.md, docs/src/design/mbus/index.md, docs/src/design/thoreir/index.md, docs/src/getting-started/contributing.md, docs/src/getting-started/supported/index.md, docs/src/getting-started/supported/package_index.md
- Building managarm guide using the `bootstrap-managarm` guide
- Short docs for hel, thor/eir, libasync, mbus, frigg, bragi, libasync.
- Added a list of packages that we have patched to work on managarm.
=> Added more docs

posix/subsystem/src/device.cpp, posix/subsystem/src/device.hpp, posix/subsystem/src/exec.cpp, posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp, posix/subsystem/src/pts.cpp, posix/subsystem/src/sysfs.cpp, posix/subsystem/src/sysfs.hpp, posix/subsystem/src/tmp_fs.cpp, posix/subsystem/src/un-socket.cpp, posix/subsystem/src/vfs.cpp, posix/subsystem/src/vfs.hpp
As requested on Discord, I have started refactoring some `FsNode` operations to use `frg::expected`. For now, I assume that nothing will throw errors, but this assumption may be wrong.
I have tested the changes and they seem to work, as in managarm boots into weston, although I fully expect there to be bugs and/or issues in this pr.
=> Refactored some FsNode operations

posix/subsystem/src/main.cpp, protocols/posix/posix.bragi
As discussed on Discord, this PR converts the following requests to bragi:
- `GET_UID`
- `SET_UID`
- `GET_EUID`
- `SET_EUID`
- `GET_GID`
- `SET_GID`
- `GET_EGID`
- `SET_EGID`
- `UNLINKAT`
- `FSTATAT`
- `MKFIFOAT`
- `LINKAT`
- `FCHMODAT`
- `UTIMENSAT`
- `RMDIR`
- `INOTIFY_ADD`
This batch should be done
=> posix: Convert requests to bragi

posix/init/src/stage2.cpp
With the runtime issues fixed, we can enable Xwayland by default
=> Init: enable xwayland

posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/tmp_fs.cpp
This PR aims to implement `seek` and `rmdir` for the tmpfs `DirectoryNode` and `DirectoryFile`.
Python uses `rmdir()` and `rewinddir()` on directories in `/tmp` when running `python3 get-pip.py`, this PR implements the required functionality.
Furthermore, this PR changes various assertions in tmpfs to proper error returns. As such, this PR closes #217
=> posix: Various additions to tmpfs

drivers/libblockfs/src/ext2fs.cpp, drivers/libblockfs/src/ext2fs.hpp, drivers/libblockfs/src/libblockfs.cpp, posix/subsystem/src/main.cpp
This PR addresses several small bugs regarding error handling in the code for `isatty()` and link counts in the ext2 driver.
=> ext2: Fix link counts

kernel/eir/arch/x86/multiboot2/multiboot2.cpp, kernel/eir/meson.build, kernel/klibc/eir/interface.hpp, kernel/thor/system/acpi/madt.cpp
This PR adds support for the multiboot 2 acpi tags and uses it where available, lai is still used as a fallback.
Part of a series of fixes for #205
=> Add support for multiboot 2 handing us the acpi tables

posix/subsystem/src/fifo.cpp, servers/netserver/src/ip/tcp4.cpp
This PR adds the ability to a FIFO pipe reader side to be non-blocking and implements `getFileFlags()` and `setFileFlags()` for a FIFO pipe reader side and tcp sockets. For the tcp sockets, this is a partial implementation, only working for `O_NONBLOCK`
=> Several non-blocking related fixes in POSIX and netserver

posix/subsystem/src/fifo.cpp, posix/subsystem/src/fifo.hpp, posix/subsystem/src/main.cpp
This PR should get rid of the message `posix: pipe2(O_NONBLOCK) is not implemented correctly` which is shown on boot.
=> posix: Implement pipe2 with O_NONBLOCK

kernel/thor/generic/service.cpp, posix/subsystem/src/epoll.cpp, posix/subsystem/src/epoll.hpp, posix/subsystem/src/exec.cpp, posix/subsystem/src/file.cpp, posix/subsystem/src/file.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/nl-socket.cpp, posix/subsystem/src/un-socket.cpp, protocols/fs/include/protocols/fs/server.hpp, protocols/fs/src/server.cpp, servers/netserver/src/ip/ip4.cpp, servers/netserver/src/ip/tcp4.cpp, servers/netserver/src/ip/udp4.cpp
This PR originally held various bugfixes for the netstack. During bug hunting, the need to refactor the sendMsg code to handle partial writes (and as such also add this to the write code) came up. Furthermore, this PR fixes a formatting error, fixes 2 critical bugs in the TCP and UDP stack, adds additional error returns in several places and adds code to handle (but not yet send) FIN TCP packets.
This PR possibly fixes #208
After this PR, managarm/mlibc#242 should be merged
=> netserver: Various bug fixes

posix/init/src/stage2.cpp
This is a hack, kmscon should invoke a login program which sets stuff like `HOME`, but as we don't have that yet, we should keep the environment as is to provide a better user experience.
=> posix-init: Don't reset the environment in kmscon

posix/subsystem/src/main.cpp, protocols/posix/posix.bragi
This PR adds a new request type in `bragi` and `posix` to support `ioctl(FIOCLEX)`. This is used by Rust's `std` to set the `CLOEXEC` flag on file descriptors.
mlibc supported is added in managarm/mlibc#259.
=> posix: Implement ioctl(FIOCLEX)

docs/src/building.md, docs/src/contributing/commit-messages.md
Some small issues slipped through QA on the last docs PR, most notably the broken links on the commit messages page. In addition to that, the name of the `gui` metapackage has changed to `weston-desktop`, so I've adjusted the docs to that as well.
=> docs: Fix some broken links and typo's and update building instructions

posix/subsystem/meson.build, posix/subsystem/src/devices/random.cpp, posix/subsystem/src/devices/random.hpp, posix/subsystem/src/devices/urandom.cpp, posix/subsystem/src/devices/urandom.hpp, posix/subsystem/src/main.cpp
This PR adds the necessary code for `/dev/random` and `/dev/urandom` based devices, and makes the `/dev/random` and `/dev/urandom` device nodes, thus providing userspace with a commonly available source of randomness.
This PR fixes #169
=> posix: Add /dev/random and /dev/urandom devices

drivers/uart/src/main.cpp, kernel/eir/arch/arm/meson.build, kernel/eir/arch/x86/meson.build, kernel/thor/meson.build
This PR is the Managarm counterpart of managarm/bootstrap-managarm#100 and fixes several issues identified under gcc 10.3. This PR is blocked on everything in managarm/bootstrap-managarm#100, with exception of this and the mlibc PR. This PR can only be merged if the mlibc PR and the bootstrap PR are also ready to be merged in order to avoid build failures.
After this PR, managarm/bootstrap-managarm#100 should be merged
=> Various fixes for gcc 10

README.md, docs/src/building.md
Fixes a few issues in the build instructions, and points the `README.md` to the handbook.
=> docs: Update build instructions

posix/subsystem/src/exec.cpp, posix/subsystem/src/main.cpp
- posix/exec: Fix order of arguments in shebang
- posix: Ignore illegal truncate targets
=> posix: Neofetch fixes

kernel/thor/generic/thor-internal/irq.hpp, kernel/thor/system/pci/dmalog.cpp
Should be merged before #319 to minimize the amount of warnings given.
=> thor: Fix several non-virtual-dtor warnings

posix/subsystem/src/subsystem/block.cpp
Should be merged before #319 to minimize the amount of warnings given.
=> posix: Fix unused parameter warning

meson.build
This PR is basically the culmination of work done in PR #287 and #288, and enables the warnings the PRs mentioned fixed. There might be a few more cases that produce warnings now in code introduced after the merging of #287 and #288, or in the aarch64 port, as I did not build that. If that turns out to be the case, a follow-up PR will fix those warnings.
=> build: Enable several warnings

README.md, docs/src/contributing/overview.md, docs/src/getting-started/supported/index.md
This PR changes our IRC location to libera.chat and adds NVMe to the list of supported hardware in both the handbook and the readme.
=> Various updates to the documentation

drivers/uart/src/main.cpp, posix/subsystem/meson.build, posix/subsystem/src/gdbserver.cpp, posix/subsystem/src/main.cpp, posix/subsystem/src/subsystem/generic.cpp, posix/subsystem/src/subsystem/generic.hpp
This PR fixes various issues with gdbserver, including not being able to use `/dev/ttyS0`. A new subsystem was added that will register `/dev/ttyS0`, I am however unsure about the major numbers used. While the numbers I've chosen now seem to be used by Linux for dynamic allocation, I did see a different number for `/dev/ttyS0`, this might need to be checked.
=> Various fixes for gdbserver

docs/src/building/index.md, docs/src/building/with-docker.md, docs/src/building/without-containers.md
This PR changes the following:
- add instructions for installing pre-built packages
- rework image creation section
[Rendered](https://github.com/managarm/managarm/blob/e2b3bb538e846a727b349a3a1ba6f71bc90bae1c/docs/src/building/index.md)
=> docs: Rework building and image creation instructions

drivers/block/ahci/src/controller.cpp, kernel/thor/generic/fiber.cpp, kernel/thor/generic/schedule.cpp, servers/netserver/src/ip/arp.hpp
This PR fixes 2 warnings and addresses 2 build failures when building with gcc 11. This will be followed up with a PR in bootstrap actually merging gcc 11 into master.
This PR complements managarm/frigg#10
=> Fixes for gcc 11

drivers/libblockfs/src/libblockfs.cpp, posix/subsystem/src/extern_fs.cpp, protocols/fs/fs.bragi
This PR changes the RENAME request from `posix-subsystem` to `libblockfs` to use a seperate bragi message, which allows for a tail and longer paths to be passed in it to `libblockfs`. This fixes a long standing issue with multiple programs when they call a rename from a long path to another long path, most notably `python3` on certain operations.
=> Refactor RENAME request to proper bragi

posix/init/src/stage1.cpp
This allows functions like `shm_open()` to work, a requirement for `gtk+-3`.
=> posix: Create /dev/shm and mount a tmpfs to it

kernel/thor/generic/core.cpp, kernel/thor/generic/thor-internal/kernel_heap.hpp, kernel/thor/generic/thor-internal/physical.hpp
Those globals are used during early initialization *before* global constructors are called.
=> Ensure allocator globals are always placed in .bss

kernel/thor/arch/arm/gic.cpp, kernel/thor/arch/x86/pic.cpp, kernel/thor/generic/debug.cpp, kernel/thor/generic/main.cpp, kernel/thor/system/pci/pci_discover.cpp, kernel/thor/system/pci/thor-internal/pci/pci.hpp
Fixes race condition in MSI vector allocation and the possibility of entering an IRQ handler between printing the panic message and the stack trace.
=> PCI MSI support and minor fixes

posix/subsystem/src/un-socket.cpp, protocols/fs/fs.bragi
This implements the `FIONREAD` ioctl managarm-side. This code appears to work with sway. On the mlibc side, PR managarm/mlibc#358 enables the use of this.
=> Implement FIONREAD ioctl

core/drm/include/core/drm/core.hpp, core/drm/src/core.cpp, drivers/gfx/bochs/src/bochs.hpp, drivers/gfx/bochs/src/main.cpp, drivers/gfx/plainfb/src/main.cpp, drivers/gfx/plainfb/src/plainfb.hpp, drivers/gfx/virtio/src/main.cpp, drivers/gfx/virtio/src/virtio.hpp, drivers/gfx/vmware/src/main.cpp, drivers/gfx/vmware/src/vmware.hpp
This PR aims to land atomic modesetting support in DRM and wiring up `vmware` and `plainfb` drivers for it. Atomic modesetting has been tested with `weston` and the [`drm-howto`](https://github.com/dvdhrm/docs/). `kmscon` does not utilize atomic modesetting.
These changes depend on managarm/mlibc#272.
=> Implement atomic modesetting in DRM

kernel/thor/meson.build, meson.build
This is related to managarm/libasync#12.
=> meson: use libasync as a subproject

drivers/usb/hcds/xhci/src/main.cpp, kernel/thor/generic/address-space.cpp, kernel/thor/generic/gdbserver.cpp, kernel/thor/generic/hel.cpp, kernel/thor/generic/ostrace.cpp, meson.build, posix/subsystem/src/gdbserver.cpp
These changes enable compilation with `-Wimplicit-fallthrough` and, while not currently enabling it, work with `-Werror` if desired.
=> meta: prepare for Werror and Wimplicit-fallthrough

posix/init/src/stage2.cpp, posix/subsystem/meson.build, posix/subsystem/src/file.cpp, posix/subsystem/src/file.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/memfd.cpp, posix/subsystem/src/memfd.hpp, posix/subsystem/src/process.cpp, posix/subsystem/src/tmp_fs.cpp, protocols/fs/fs.bragi, protocols/fs/include/protocols/fs/server.hpp, protocols/fs/src/server.cpp, protocols/posix/posix.bragi, testsuites/posix-tests/meson.build, testsuites/posix-tests/src/memfd.cpp
The `MemoryFile` used here is an adapted version of the same struct in tmpfs, stripped of some functionality not yet needed.
=> posix: implement memfd and file sealing

posix/init/src/stage2.cpp, posix/subsystem/src/main.cpp, posix/subsystem/src/nl-socket.cpp, posix/subsystem/src/nl-socket.hpp
This PR fixes a hang in `kmscon` caused by the use of a `O_NONBLOCK` netlink socket in `eudev`. Since we don't support that yet, the call to `recvmsg` never returns.
We implement the required functionality and also modify init to block on the call to `udev_monitor_receive_device`, as would have happened before.
See also https://github.com/managarm/mlibc/pull/379 which fixes some further boot failures with this patch.
=> posix: implement O_NONBLOCK for netlink

posix/subsystem/src/drvcore.cpp
`WebKitGTK` tries to connect to a netlink socket with `NETLINK_ROUTE`. By creating this group, this connect operation won't fail, allowing `WebKitGTK` to continue further in boot.
=> posix: Create a NETLINK_ROUTE group

core/virtio/include/core/virtio/core.hpp
This makes `netserver` not die randomly anymore, and is required for `webkitgtk` to load webpages.
=> core/virtio: Fix use-after-free in Queue

drivers/usb/hcds/uhci/src/main.cpp
The progressSchedule function runs queue entries which potentially add more entries into the list of things that progressSchedule is iterating.  If the vector allocates more memory to accomdate the addition then the C++ spec says that all iterators are invalidated and thus the function will iterate in a bad way, probably right off the end and into undefined memory causing a GPF
=> UHCI: Fixed a modify while iterating bug

posix/subsystem/src/file.cpp, posix/subsystem/src/file.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/pts.cpp, protocols/posix/posix.bragi
If a session leader opens a terminal device without using O_NOCTTY then it should become the controlling terminal if the controlling terminal is not present.
Note: This depends on https://github.com/managarm/mlibc/pull/409
=> posix: Set the controlling terminal of the process on open

posix/subsystem/src/main.cpp, posix/subsystem/src/process.cpp, posix/subsystem/src/process.hpp
When receiving a kill syscall, check if the PID is less than 0 and if so kill the entire group.  Also, apply the todo logic in the kill(0) path so that the entire group of the running process is killed
=> posix: Implement killpg(int, int) support

drivers/libblockfs/src/libblockfs.cpp, posix/subsystem/src/file.cpp, posix/subsystem/src/file.hpp, posix/subsystem/src/tmp_fs.cpp, protocols/fs/fs.bragi, protocols/fs/include/protocols/fs/server.hpp, protocols/fs/src/server.cpp
While we've had `pread()` for a while now, `pwrite()` wasn't implemented. This PR adds `pwrite()` support for ext2 and tmpfs, which pleases `gtk3`, specifically `dconf`.
A corresponding mlibc PR will be provided shortly.
=> Implement pwrite

core/drm/meson.build, hel/meson.build, mbus/meson.build, posix/subsystem/meson.build, protocols/fs/meson.build, protocols/hw/meson.build, protocols/kernlet/meson.build, protocols/mbus/meson.build, protocols/ostrace/meson.build, protocols/usb/meson.build
Some userspace programs didn't do this correctly. This is needed when we move the frigg headers from `/usr/include/frg` to `/usr/share/frigg/include/frg`, since the latter isn't picked up automatically.
=> meson: declare frigg as a dependency everywhere

posix/subsystem/src/pts.cpp
=> posix: implement get/set flags on pts

posix/subsystem/src/file.cpp, posix/subsystem/src/file.hpp, posix/subsystem/src/tmp_fs.cpp
This PR implements `pread()` for `tmpfs`. Used by `gtk3` and `Chromium`.
Part of the Chromium on Managarm project.
=> posix: Implement pread for tmp_fs

posix/subsystem/src/main.cpp, protocols/fs/src/server.cpp
This PR adds various fixes in order to run `hexchat` on Managarm. For now, this consist of better error handling in `sendMsg` and handling unknown address families gracefully in the socket request. I fully expect more to come and as such, this PR is a draft.
The mlibc counterpart to this PR is managarm/mlibc#273
=> Various fixes for hexchat

core/drm/include/core/drm/core.hpp, core/drm/meson.build, core/drm/src/core.cpp, hel/include/helix/ipc-structs.hpp, hel/include/helix/ipc.hpp, kernel/thor/generic/credentials.cpp, kernel/thor/generic/hel.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/thor-internal/credentials.hpp, kernel/thor/generic/thor-internal/main.hpp, kernel/thor/generic/thor-internal/stream.hpp, kernel/thor/generic/thor-internal/thread.hpp, kernel/thor/generic/thread.cpp, kernel/thor/meson.build, posix/subsystem/src/device.cpp, posix/subsystem/src/device.hpp, posix/subsystem/src/file.hpp, posix/subsystem/src/main.cpp, protocols/fs/fs.bragi, protocols/posix/posix.bragi
This is rough code for making the PRIME ioctls work for sway. The code is not optimal and the naming is weird, but I couldn't come up with something better.
Posting as draft, as I don't expect this to survive review unchanged.
mlibc counterpart is managarm/mlibc#367.
=> posix: implement PRIME for fd <-> handle conversion

kernel/eir/arch/x86/multiboot1/multiboot1.cpp, kernel/thor/system/acpi/madt.cpp
closes #125, and fully shifts ACPI scanning out of the kernel
=> eir: scan for RSDP when booting with multiboot1

posix/subsystem/src/sockutil.hpp
```
Excerpt from mlibcs sys/socket.h:
// Control message format:
// The offsets marked with ^ are aligned to alignof(size_t).
//
// |---HEADER---|---DATA---|---PADDING---|---HEADER---|...
// ^            ^                        ^
// |---------CMSG_LEN------|
// |---------------CMSG_SPACE------------|
Currently, CtrlBuilder pushes DATA right up against HEADER, without any
room for the few bytes of padding that exist when HEADERs right boundary
is not aligned against alignof(sizeof_t). This patch corrects that by
aligning the size of the header up to alignof(size_t).
```
Mutual blocker with https://github.com/managarm/mlibc/pull/728
=> posix/subsystem: account for padding size in CtrlBuilder

kernel/thor/arch/x86/paging.cpp, kernel/thor/arch/x86/thor-internal/arch/paging.hpp, kernel/thor/generic/address-space.cpp, kernel/thor/generic/thor-internal/address-space.hpp
This PR improves performance of common paging operations, see the commit message of the second commit.
The first commit optimizes large shootdowns by reloading CR3 instead of calling `invlpg` hundreds of times. This also gives a considerable speedup when unmapping pages.
=> thor: Use cursors to implement VirtualOperations on x86

protocols/fs/src/server.cpp
I found this while testing `libremines` on Qt 6.4, easy fix which should probably have been here from the start.
=> protocols/fs: Guard the call to getSeals with a nullptr check

posix/subsystem/src/requests.cpp
This fixes `curl` crashing with unknown poll events and together with two mlibc PRs allows `curl` to work.
=> posix: Handle POLLWRNORM in the poll request

posix/subsystem/src/file.cpp, protocols/fs/src/server.cpp
This fixes some crashes in `glxgears` during shutdown.
=> posix+protocols/fs: Handle writes to an unconnected socket

core/drm/src/ioctl.cpp, drivers/clocktracker/src/main.cpp, drivers/kernletcc/src/main.cpp, drivers/libblockfs/src/libblockfs.cpp, drivers/libevbackend/src/libevbackend.cpp, drivers/tty/virtio-console/src/console.cpp, drivers/uart/src/main.cpp, posix/subsystem/src/clock.cpp, posix/subsystem/src/device.cpp, posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/subsystem/input.cpp, posix/subsystem/src/vfs.cpp, servers/netserver/src/main.cpp, utils/runsvr/src/main.cpp
This PR addresses some missing reset calls after the use of a buffer that was received with `recvInline`. This should catch all uses in the Managarm codebase. Note that some of the users already did this, so not all users have been changed.
=> Some bragi recvInline fixes

posix/subsystem/src/requests.cpp
Calling `associatedLink` on files that don't support it can lead to trying to call nullptr's. As this is bad, I figured that returning ENOENT is a good fallback (while keeping the log about which kind of file is being called intact).
=> posix: Guard against nullptrs in FSTATAT request

posix/subsystem/src/extern_fs.cpp, protocols/fs/fs.bragi, protocols/fs/src/server.cpp
As paths can become quite large, we should use the new bragi style messages with a variable sized tail to communicate those paths in `NODE_TRAVERSE_LINKS`. This fixes crashes on long paths, as I managed to trigger with Chromium.
Part of the Chromium on Managarm project.
=> protocols/fs: Refactor the NODE_TRAVERSE_LINKS request to bragi

posix/subsystem/src/procfs.cpp
Fixes a nullptr crash in the WebKit MiniBrowser.
=> posix: Fix /proc/[pid]/maps if they contain SpecialLinks

posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp
This PR adds the `/proc/[pid]/comm` and `/proc/[pid]/root` nodes, exposing more information that might be of use to the userspace. They should both match Linux from what I can tell.
=> posix: Add /proc/[pid]/comm and /proc/[pid]/root

posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp
This PR adds initial versions of `/proc/[pid]/stat` and `/proc/[pid]/statm`. While they lack a lot of information, their structure matches what is in my man pages (see the comments in the file). Having these files available with the information they provide, they allow `htop` to at least show the running processes, their pid and their name.
=> posix: Add /proc/[pid]/{stat,statm}

posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp
This PR adds two new nodes in `/proc`, namely `/proc/[pid]/status` and `/proc/[pid]/cwd`. While the `status` node is lacking in comparison to the Linux counterpart, it does expose some information we didn't export before, and the layout matches what I have in my man page (see the comments in the file for more explanation). The `cwd` node is behaving the same as the Linux version, minus perhaps some permission stuff.
=> posix: Add /proc/[pid]/{status,cwd}

drivers/libevbackend/src/libevbackend.cpp
=> drivers/libevbackend: fix typo'd ioctl name

servers/netserver/src/ip/ip4.cpp, servers/netserver/src/ip/ip4.hpp
These were previously part of #510, but got dropped mistakenly.
=> netserver: implement operators for `CidrAddress` and `Route`

posix/subsystem/src/requests.cpp, protocols/posix/posix.bragi
`WebKitGTK` did some long paths on `ACCESSAT` and `MKDIRAT`, so I rewrote them to account for this.
Blocked on managarm/mlibc#822
=> posix: Rewrite two bragi messages to use the new format

drivers/nic/virtio/src/virtio.cpp
Reduces e9 spam by a lot when working with `WebKitGTK`.
=> drivers/nic/virtio: Put the sending and sent frame logs behind a guard

posix/subsystem/src/exec.cpp
The first fix is allowing read only mappings in libraries, ICU loves them.
The second fix is ignoring `PT_NOTE`, as we should.
=> Two exec fixes required for chromium

kernel/thor/generic/debug.cpp, kernel/thor/generic/thor-internal/debug.hpp, kernel/thor/system/pci/pci_discover.cpp, kernel/thor/system/pci/thor-internal/pci/pci.hpp
Closes #451.
Also fixes panic messages being truncated after first 256 bytes.
=> thor: Fix PCI MSI handling around EnableMsi and InstallMsi requests

posix/subsystem/src/un-socket.cpp
Add a SpecialLink link to unix sockets, because it allows stat to work on them.
=> posix/un-socket: Add a SpecialLink link

posix/subsystem/src/net.cpp, protocols/fs/fs.bragi, servers/netserver/src/main.cpp, servers/netserver/src/netlink/netlink.cpp, servers/netserver/src/netlink/netlink.hpp
I'm pretty sure 'WebKitGTK' needed it, but we don't see it called. The `SO_PASSCRED` implementation is lacking things, but it works for 'WebKitGTK', so I want it in.
Supercedes #526
=> netserver: Stub netlink SO_PASSCRED

kernel/eir/arch/x86/multiboot2/multiboot2.cpp
The first commit enables booting one some machines using MB2, where the LFB returned by firmware is above 4 GiB. In this case, eir doesn't use the framebuffer, but maps it for thor and passes it on.
The second commit makes booting without a framebuffer work with MB2. This will be useful for testing coldbooting GPUs, aka where firmware doesn't set them up, where we won't get a framebuffer passed.
=> eir: allow booting with limited or no framebuffer support on MB2

hel/include/hel.h, kernel/thor/generic/hel.cpp, posix/subsystem/src/process.cpp
Change signal code to pass ucontext to signal handlers and add a kHelRegsSignal registerset that matches the linux layout to helLoadRegisters/helStoreRegisters/helQueryRegisterInfo.
=> posix: Pass ucontext to signal handlers

posix/subsystem/src/file.cpp, posix/subsystem/src/sysfs.cpp, posix/subsystem/src/sysfs.hpp, protocols/fs/src/server.cpp
`lsblk` was crashing posix on seeking on a sysfs directory. Return EINVAL for now and add some error handling while we're at it.
mlibc counterpart to be provided shortly.
=> Sysfs seeking improvements

posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp
This time I decided to tackle some low hanging fruits in `/proc/sys/kernel`, so here are `ostype` (Managarm), `osrelease` (0.0.1) and `arch` (set to either `x86_64` or `AArch64` depending on architecture).
=> More proc additions

drivers/libblockfs/src/libblockfs.cpp, posix/subsystem/src/subsystem/block.cpp, protocols/fs/fs.bragi
This PR exposes some more attributes over sysfs for blockdevices. Most are hardcoded to a sane value (R/O is always zero), some are just a placeholder (size being 3.3G) and some are correct (major:minor number). This makes `lsblk` show `sda0`!
=> General sysfs block improvements

kernel/thor/generic/main.cpp, kernel/thor/generic/mbus.cpp, kernel/thor/generic/thor-internal/mbus.hpp, kernel/thor/system/pci/pci_discover.cpp, kernel/thor/system/pci/thor-internal/pci/pci.hpp, posix/subsystem/src/drvcore.cpp, posix/subsystem/src/drvcore.hpp, posix/subsystem/src/subsystem/block.cpp, posix/subsystem/src/subsystem/drm.cpp, posix/subsystem/src/subsystem/pci.cpp, posix/subsystem/src/subsystem/usb/usb.cpp, protocols/hw/src/client.cpp
This allows for `lspci -tv` and `lspci -vv` to work as intended.
=> Correctly expose PCI hierarchy in sysfs

kernel/thor/generic/thor-internal/futex.hpp
This happens not because of a race condition, but because the futex has already been woken up and some stragglers may still be canceling it.
=> thor: correct futex cancel fix

posix/subsystem/src/requests.cpp, posix/subsystem/src/sysfs.cpp, posix/subsystem/src/tmp_fs.cpp, testsuites/posix-tests/src/faults.cpp, testsuites/virt-test/main.cpp
Fix initialization order and properly cast variables between signed/unsigned when doing compares.
=> posix: Fix most compiler warnings

hel/meson.build
These are needed by the generic hel-stubs.h which is used in hel-syscalls.h.
=> hel: Install arch-specific syscall stub headers

posix/subsystem/src/subsystem/usb/root-hub.hpp, posix/subsystem/src/subsystem/usb/usb.cpp
Add support for USB 3.1. I am not completely sure if SuperSpeedPlus also has some kind of companion descriptor different from the SuperSpeed one so thats something to check (though by a quick look at the specification I didn't find anything else than SuperSpeedPlus isochronous companion descriptor which probably isn't something the hub should have).
=> posix: Support USB 3.1

protocols/usb/src/client.cpp, protocols/usb/src/server.cpp
Send the buffer size in the response to support larger descriptors than recvInline() can handle.
=> protocols/usb: Support large configuration descriptors

posix/subsystem/src/requests.cpp
=> posix: Use SIG_DFL and SIG_IGN instead of hardcoding values in SIG_ACTION

drivers/libblockfs/src/ext2fs.cpp, drivers/libblockfs/src/ext2fs.hpp, drivers/libblockfs/src/libblockfs.cpp, posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp, posix/subsystem/src/requests.cpp, posix/subsystem/src/tmp_fs.cpp, protocols/fs/fs.bragi
We used to just initialize everything to zero, which is fine as long as we're root. I plan on adding more support for multiple users in the near future, so expect more fixes in this category.
=> libblockfs/ext2: Set uid/gid when creating new files

kernel/eir/arch/arm/fault.S, kernel/eir/arch/arm/generic.cpp, kernel/eir/arch/arm/meson.build, kernel/eir/arch/arm/raspi4/raspi4.S, kernel/eir/arch/arm/raspi4/raspi4.cpp, kernel/eir/arch/arm/virt/link.x, kernel/eir/arch/arm/virt/meson.build, kernel/eir/arch/arm/virt/virt.S, kernel/eir/arch/arm/virt/virt.cpp, kernel/eir/generic/eir-internal/arch.hpp, kernel/eir/generic/eir-internal/generic.hpp, kernel/klibc/elf.h
Merge common duplicated aarch64 eir init code and make it a pie on virt platform. It would also likely be possible to do that on raspi4 but I don't really know how the bootloader handles images with base address zero (and if it would be non-zero it would need to be taken into account somehow in eirRelocate() or alternatively making sure there are no relocations at all but that requires some ugly hacks eg. around constexpr string arrays in fault.cpp).
=> kernel/eir: Merge common aarch64 init code and make virt eir pie

kernel/eir/arch/arm/generic.cpp, kernel/eir/generic/debug.cpp, kernel/thor/system/dtb/dtb.cpp
I am not sure if `logNodeInfo` should be kept enabled, I disabled it because it slows the boot significantly when there are ~1k nodes.
=> More aarch64 fixes

kernel/thor/arch/arm/smp.cpp, kernel/thor/system/dtb/thor-internal/dtb/dtb.hpp
Initialize cpuOn_ to psci sm64 cpu-on method by default, change cpu id to be 64-bit and add more psci/cpu compatibility strings.
=> Aarch64 smp fix

drivers/libblockfs/src/libblockfs.cpp, protocols/fs/src/server.cpp
Depends on managarm/mlibc#1047.
Previously, running `cat` on a directory returned garbage. With this change, it correctly outputs `cat: <directory>: Is a directory`.
=> Implement EISDIR for read

kernel/thor/arch/arm/link.x, kernel/thor/arch/x86/link.x
Add .data.* and .bss.* sections to some linker scripts.
=> thor: Add missing data/bss sections to linker scripts

posix/subsystem/src/epoll.cpp
If the item is pending, we need to remove it from the pending queue before we cancel polling, as that's what the logic in _awaitPoll expects.
=> posix: Fix order of operations in epoll handleClose

core/drm/src/ioctl.cpp, hel/include/hel-stubs-aarch64.h, hel/include/hel-stubs-x86_64.h, hel/include/hel-syscalls.h, hel/include/hel.h, hel/include/helix/ipc.hpp, kernel/thor/generic/credentials.cpp, kernel/thor/generic/hel.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/stream.cpp, kernel/thor/generic/thor-internal/credentials.hpp, kernel/thor/generic/thor-internal/stream.hpp
9278db8d27369933de57b0657d488604b3675d15 broke sway, so this PR attaches credentials to `Stream`s again. In order to keep the objective of that commit, these are only generated on demand.
=> Attach credentials to streams again

posix/subsystem/src/subsystem/usb/attributes.cpp, posix/subsystem/src/subsystem/usb/attributes.hpp, posix/subsystem/src/subsystem/usb/devices.hpp, posix/subsystem/src/subsystem/usb/usb.cpp
This allows for running `lsusb.py` with the `-e` flag.
=> posix: expose USB endpoints on sysfs

core/lib/bpf/bpf.cpp, drivers/nic/usb_ecm/include/nic/usb_ecm/usb_ecm.hpp, drivers/nic/usb_ecm/meson.build, drivers/nic/usb_ecm/src/usb-ecm.cpp, drivers/usb/90-managarm-usb.rules, drivers/usb/hcds/ehci/src/ehci.hpp, drivers/usb/hcds/ehci/src/main.cpp, drivers/usb/hcds/uhci/src/main.cpp, drivers/usb/hcds/uhci/src/schedule.hpp, drivers/usb/hcds/xhci/src/main.cpp, drivers/usb/hcds/xhci/src/xhci.hpp, meson.build, posix/subsystem/src/subsystem/usb/attributes.cpp, posix/subsystem/src/subsystem/usb/devices.hpp, posix/subsystem/src/subsystem/usb/usb.cpp, protocols/usb/include/protocols/usb/api.hpp, protocols/usb/include/protocols/usb/usb.hpp, protocols/usb/src/api.cpp, protocols/usb/src/client.cpp, protocols/usb/src/server.cpp, protocols/usb/usb.bragi, servers/netserver/include/netserver/nic.hpp, servers/netserver/meson.build, servers/netserver/src/main.cpp
This PR adds support for USB ethernet adapters that support ECM, and fixes some bugs along the way. In order to test this, qemu's `-device usb-net` can be used. A PR to wire this up in vm-util has already been made (managarm/bootstrap-managarm#343).
=> USB-to-ethernet adapter support

posix/subsystem/src/requests.cpp
this fixes a bug where if you unlink a symlink, you unlink the file the symlink is actually pointing to
=> posix: dont follow symlink on unlink

kernel/thor/generic/main.cpp, posix/subsystem/src/debug-options.hpp, posix/subsystem/src/observations.cpp
Logging handled page faults mostly just adds unnecessary noise to the log when running eg. java/wine so disable it by default and add an option to log them in case its needed for debugging.
=> Don't log handled page faults by default

drivers/libblockfs/src/libblockfs.cpp, posix/init/src/stage1.cpp, posix/subsystem/src/subsystem/block.cpp, posix/subsystem/src/vfs.cpp
Now all partitions are exposed in /dev and /sys, and init-stage1 finds the root partition by looking for one with the appropriate type in the partition table.
=> libblockfs and init-stage1 improvements

.github/workflows/ci.yml, hel/include/helix/passthrough-fd.hpp, hel/meson.build, hel/src/passthrough-fd.cpp, meson.build, posix/subsystem/src/devices/helout.cpp, posix/subsystem/src/tmp_fs.cpp, posix/subsystem/src/vfs.cpp
This avoids having to (hackily) rely on `__mlibc_getPassthrough`.
=> helix: add handleForFd function

drivers/kbd/meson.build, drivers/kbd/src/main.cpp, drivers/kbd/src/ps2.hpp, drivers/kbd/src/spec.hpp, kernel/thor/meson.build, kernel/thor/system/acpi/acpi.cpp, kernel/thor/system/acpi/battery.cpp, kernel/thor/system/acpi/ps2.cpp, kernel/thor/system/acpi/thor-internal/acpi/acpi.hpp, kernel/thor/system/acpi/thor-internal/acpi/ps2.hpp, kernel/thor/system/legacy-pc/ata.cpp, kernel/thor/system/pci/pci_discover.cpp, posix/subsystem/src/subsystem/acpi.cpp, protocols/hw/hw.bragi, protocols/hw/include/protocols/hw/client.hpp, protocols/hw/src/client.cpp, protocols/mbus/include/protocols/mbus/client.hpp, protocols/mbus/src/client_ng.cpp
This PR enables detection of i8042 parameters (I/O ports, IRQ numbers) via ACPI.
=> PS/2 driver rework for ACPI detection support

docs/src/contributing/lsp.md, hel/meson.build, kernel/eir/arch/arm/load64.S, kernel/eir/arch/riscv/entry64.S, kernel/eir/arch/x86/load64.S, kernel/eir/arch/x86/meson.build, kernel/eir/generic/debug.cpp, kernel/eir/generic/eir-internal/debug.hpp, kernel/eir/meson.build, kernel/eir/protos/uefi/efi.hpp, kernel/eir/protos/uefi/entry.cpp, kernel/eir/protos/uefi/helpers.cpp, kernel/eir/protos/uefi/helpers.hpp, kernel/eir/protos/uefi/meson.build, kernel/memory.txt, kernel/thor/meson.build, meson.build, meson_options.txt, testsuites/kernel-bench/meson.build
This PR adds UEFI as a boot protocol to eir. It's architecture independent and introduces a "protos" directory for future independent protocols.
=> eir: add UEFI boot protocol

.github/workflows/ci.yml
Simplify the CI workflow by using the new `auto_pull` feature of xbstrap.
=> ci: Use auto_pull instead of listing all deps

core/include/core/logging.hpp, core/meson.build, drivers/kbd/src/main.cpp, drivers/libevbackend/include/libevbackend.hpp, drivers/libevbackend/src/libevbackend.cpp, drivers/usb/devices/hid/meson.build, drivers/usb/devices/hid/src/handler/multitouch.cpp, drivers/usb/devices/hid/src/handler/multitouch.hpp, drivers/usb/devices/hid/src/hid.hpp, drivers/usb/devices/hid/src/main.cpp, drivers/usb/devices/hid/src/quirks.cpp, drivers/usb/devices/hid/src/quirks.hpp, drivers/usb/devices/hid/src/quirks/wacom.cpp, drivers/usb/devices/hid/src/quirks/wacom.hpp, drivers/usb/devices/hid/src/spec.hpp, protocols/fs/fs.bragi
Before this, HID assertions prevented my test laptop from booting managarm; these commits handle the missing bits in the report descriptors and improve the information given to userspace by the `EVIOCGID` and `EVIOCGNAME` ioctls.
=> HID: fixes and improvements for better touchscreen support

docs/src/building/index.md
Update the docs to use the `auto_pull: true` feature. This makes it unnecessary to manually run `xbstrap pull-pack` / `xbstrap download-tool-archive`.
=> docs: Update to recommend auto_pull

kernel/thor/arch/arm/cpu.cpp, kernel/thor/arch/arm/gic_v2.cpp, kernel/thor/arch/arm/ints.cpp, kernel/thor/arch/arm/smp.cpp, kernel/thor/arch/arm/system.cpp, kernel/thor/arch/arm/thor-internal/arch/cpu.hpp, kernel/thor/arch/arm/thor-internal/arch/gic.hpp, kernel/thor/arch/arm/thor-internal/arch/gic_v2.hpp, kernel/thor/arch/arm/timer.cpp, kernel/thor/arch/x86/hpet.cpp, kernel/thor/arch/x86/ints.cpp, kernel/thor/arch/x86/svm.cpp, kernel/thor/arch/x86/system.cpp, kernel/thor/arch/x86/thor-internal/arch/cpu.hpp, kernel/thor/arch/x86/vmx.cpp, kernel/thor/generic/fiber.cpp, kernel/thor/generic/kasan.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/random.cpp, kernel/thor/generic/schedule.cpp, kernel/thor/generic/thor-internal/arch-generic/cpu.hpp, kernel/thor/generic/thor-internal/cpu-data.hpp, kernel/thor/generic/thor-internal/fiber.hpp, kernel/thor/generic/thor-internal/kasan.hpp, kernel/thor/generic/thread.cpp, kernel/thor/system/acpi/madt.cpp, kernel/thor/system/framebuffer/fb.cpp
arch-generic/cpu.hpp provides the interface between the generic and architecture-specific code, and validates that structures defined in arch/cpu.hpp meet the requirements of the generic code.
=> thor: Move out common arch/cpu.hpp definitions to a shared file

kernel/thor/arch/arm/debug.cpp, kernel/thor/arch/arm/thor-internal/arch/debug.hpp, kernel/thor/arch/x86/debug.cpp, kernel/thor/arch/x86/thor-internal/arch/debug.hpp, kernel/thor/generic/debug.cpp, kernel/thor/generic/hel.cpp, kernel/thor/generic/kernel-log.cpp, kernel/thor/generic/thor-internal/debug.hpp, kernel/thor/system/framebuffer/boot-screen.cpp, kernel/thor/system/framebuffer/thor-internal/framebuffer/boot-screen.hpp
This drastically reduces the number of virtual calls in the logging path. It is also makes it easier to make logging re-entrant (such that we can properly log from NMIs and MCEs).
=> thor: Rework LogHandler to use single emit() call

kernel/thor/generic/kernel-log.cpp
All log lines should be smaller than logLineLength (+ 1 for null terminator). We use a small_vector instead of an array mainly because of frg::output_to (and it helps keep the changes minimal).
=> thor: Use small_vector in KmsgLogHandler to avoid allocations

.clang-format, .clang-format-include, hel/include/hel-stubs-riscv64.h, hel/include/hel-stubs.h, hel/include/hel.h, hel/meson.build, kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/debug.cpp, kernel/thor/arch/riscv/entry.S, kernel/thor/arch/riscv/link.x, kernel/thor/arch/riscv/meson.build, kernel/thor/arch/riscv/paging.cpp, kernel/thor/arch/riscv/stubs.S, kernel/thor/arch/riscv/stubs.cpp, kernel/thor/arch/riscv/system.cpp, kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp, kernel/thor/arch/riscv/thor-internal/arch/debug.hpp, kernel/thor/arch/riscv/thor-internal/arch/ints.hpp, kernel/thor/arch/riscv/thor-internal/arch/paging.hpp, kernel/thor/arch/riscv/thor-internal/arch/stack.hpp, kernel/thor/arch/riscv/thor-internal/arch/system.hpp, kernel/thor/arch/riscv/thor-internal/arch/unimplemented.hpp, kernel/thor/arch/riscv/unimplemented.cpp, kernel/thor/generic/gdbserver.cpp, kernel/thor/generic/hel.cpp, kernel/thor/meson.build
This PR makes thor compile, even though it (obviously) does not work yet.
We also use clang-format for the newly added files in `kernel/thor/arch/riscv` and add the appropriate configuration files for that purpose.
Original code by @ElectrodeYT, rebased by @no92 and rebased again by me.
Supersedes #534.
=> Add RISC-V support to thor

kernel/thor/arch/arm/cpu.cpp, kernel/thor/arch/arm/debug.cpp, kernel/thor/arch/arm/smp.cpp, kernel/thor/arch/arm/thor-internal/arch/cpu.hpp, kernel/thor/arch/arm/thor-internal/arch/debug.hpp, kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp, kernel/thor/arch/x86/cpu.cpp, kernel/thor/arch/x86/debug.cpp, kernel/thor/arch/x86/ints.cpp, kernel/thor/arch/x86/iseq.S, kernel/thor/arch/x86/meson.build, kernel/thor/arch/x86/thor-internal/arch/cpu.hpp, kernel/thor/arch/x86/thor-internal/arch/debug.hpp, kernel/thor/generic/core.cpp, kernel/thor/generic/debug.cpp, kernel/thor/generic/thor-internal/arch-generic/cpu.hpp, kernel/thor/generic/thor-internal/cpu-data.hpp, kernel/thor/generic/thor-internal/debug.hpp, kernel/thor/generic/thor-internal/ring-buffer.hpp
This overhauls the logging infrastructure to allow re-entrant logging. In particular, this enables logging from NMI, MCE and other contexts that cannot be masked. To achieve this, we add a mechanism for code sequences that can be interrupted (and cancelled) by NMIs and similar exceptions. The new mechanism is similar to the existing user access region (UAR) infrastructure. We use the new mechanism to implement an interruptible memcpy() to a per-CPU logging ring buffer.
=> Make logging re-entrant

kernel/thor/arch/arm/ints.cpp, kernel/thor/arch/arm/thor-internal/arch/ints.hpp, kernel/thor/arch/riscv/ints.cpp, kernel/thor/arch/riscv/thor-internal/arch/ints.hpp, kernel/thor/arch/x86/ints.cpp, kernel/thor/arch/x86/pic.cpp, kernel/thor/arch/x86/stubs.S, kernel/thor/arch/x86/thor-internal/arch/ints.hpp, kernel/thor/arch/x86/thor-internal/arch/pic.hpp, kernel/thor/generic/asid.cpp, kernel/thor/generic/int-call.cpp, kernel/thor/generic/schedule.cpp, kernel/thor/generic/thor-internal/arch-generic/ints.hpp, kernel/thor/generic/thor-internal/cpu-data.hpp, kernel/thor/generic/thor-internal/int-call.hpp, kernel/thor/meson.build
This adds a helper call to invoke a function via an IPI. For example, this can be used to "escape" NMI and exception contexts.
Usage:
```c++
SelfIntCall foo {[] {
infoLogger() << "Hello from foo in IPI context" << frg::endlog;
}};
foo.schedule();
```
=> kernel/thor: Add SelfIntCall infrastructure

kernel/thor/arch/arm/debug.cpp, kernel/thor/arch/arm/thor-internal/arch/debug.hpp, kernel/thor/arch/riscv/debug.cpp, kernel/thor/arch/riscv/thor-internal/arch/debug.hpp, kernel/thor/arch/x86/debug.cpp, kernel/thor/arch/x86/thor-internal/arch/debug.hpp, kernel/thor/generic/debug.cpp, kernel/thor/generic/kerncfg.cpp, kernel/thor/generic/kernel-log.cpp, kernel/thor/generic/thor-internal/debug.hpp, kernel/thor/generic/thor-internal/kernel-log.hpp, kernel/thor/generic/thor-internal/ring-buffer.hpp, kernel/thor/system/framebuffer/boot-screen.cpp, kernel/thor/system/framebuffer/thor-internal/framebuffer/boot-screen.hpp
This enables in-kernel log consumers that cannot run in NMI or exception contexts. We also update the kmsg code to read records from the new global log ring (instead of using a `LogHandler`). This is necessary because memory allocations / async waiting etc. done by the kmsg code are not NMI safe.
=> thor: Add GlobalLogRing for raw log records

kernel/eir/protos/uefi/helpers.cpp
u-boot's EFI implementation returns EFI_INVALID_PARAMETER when the buffer pointer is a nullptr. This commit avoids this by passing a dummy efi_file_info, with a unreasonably small size to allow for allocating a properly sized area later.
=> eir/uefi: make fsGetInfo work on u-boot

kernel/common/riscv/csr.hpp, kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/ints.cpp, kernel/thor/arch/riscv/meson.build, kernel/thor/arch/riscv/paging.cpp, kernel/thor/arch/riscv/stubs.S, kernel/thor/arch/riscv/stubs.cpp, kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp, kernel/thor/arch/riscv/thor-internal/arch/ints.hpp, kernel/thor/arch/riscv/trap.cpp, kernel/thor/arch/riscv/user-access.S, kernel/thor/system/dtb/dtb.cpp, kernel/thor/system/pci/pci_acpi.cpp, kernel/thor/system/pci/pci_discover.cpp, kernel/thor/system/pci/pci_dtb.cpp, kernel/thor/system/pci/thor-internal/pci/pci.hpp
This allows userspace to advance further (in particular, ping IPIs are required to ensure that userspace does not get stuck in the idle task).
=> thor: Enable IRQs on RISC-V

kernel/eir/arch/arm/eir-internal/arch/types.hpp, kernel/eir/arch/arm/generic.cpp, kernel/eir/arch/arm/load64.S, kernel/eir/arch/riscv/stubs.S, kernel/eir/arch/x86/load32.S, kernel/eir/arch/x86/load64.S, kernel/eir/generic/main.cpp, kernel/klibc/eir/interface.hpp, kernel/klibc/elf.h, kernel/thor/arch/arm/entry.S, kernel/thor/arch/arm/link.x, kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/entry.S, kernel/thor/arch/riscv/link.x, kernel/thor/arch/x86/entry.S, kernel/thor/arch/x86/link.x, kernel/thor/generic/core.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/physical.cpp, kernel/thor/generic/thor-internal/elf-notes.hpp, kernel/thor/generic/thor-internal/main.hpp, kernel/thor/generic/thor-internal/physical.hpp, kernel/thor/system/acpi/madt.cpp, kernel/thor/system/dtb/dtb.cpp
Instead of magic constants, we now take the memory layout dynamically from Eir (however, as of this PR, Eir itself still determines it statically).
This is achieved by adding an ELF note into `thor` that is patched at load time by Eir.
=> kernel/thor: Remove magic memory layout constants

kernel/eir/arch/arm/arch.cpp, kernel/eir/arch/arm/generic.cpp, kernel/eir/arch/riscv/arch.cpp, kernel/eir/arch/riscv/paging.cpp, kernel/eir/arch/x86/arch.cpp, kernel/eir/generic/eir-internal/memory-layout.hpp, kernel/eir/generic/main-function.cpp, kernel/eir/generic/main.cpp, kernel/eir/generic/memory-layout.cpp, kernel/eir/meson.build, kernel/memory.txt
This determines the virtual memory layout of Thor from the platform's number of virtual address bits.
=> kernel/eir: Determine memory layout at runtime

kernel/thor/arch/arm/cpu.cpp, kernel/thor/arch/arm/thor-internal/arch/cpu.hpp, kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp, kernel/thor/arch/riscv/thor-internal/arch/trap.hpp, kernel/thor/arch/riscv/trap.cpp, kernel/thor/arch/x86/cpu.cpp, kernel/thor/arch/x86/thor-internal/arch/cpu.hpp, kernel/thor/generic/schedule.cpp, kernel/thor/generic/thor-internal/arch-generic/cpu.hpp, kernel/thor/generic/thor-internal/cpu-data.hpp, kernel/thor/generic/thread.cpp
This PR brings some minor improvements to the RISC-V code. The next missing piece in userspace is to implement `helLoadRegisters`/`helStoreRegisters` to enable POSIX to `exec()`.
=> thor: Implement workOnExecutor on RISC-V, rework FP handling

kernel/eir/arch/arm/generic.cpp, kernel/eir/arch/arm/virt/meson.build, kernel/eir/arch/arm/virt/virt.S, kernel/eir/arch/arm/virt/virt.cpp, kernel/eir/arch/riscv/dtb.cpp, kernel/eir/arch/riscv/entry64.S, kernel/eir/arch/riscv/platform/virt/link.x, kernel/eir/arch/riscv/platform/virt/meson.build, kernel/eir/arch/x86/arch.cpp, kernel/eir/generic/debug.cpp, kernel/eir/generic/eir-internal/main.hpp, kernel/eir/generic/elf-relocate.cpp, kernel/eir/generic/main-function.cpp, kernel/eir/generic/main.cpp, kernel/eir/protos/uefi/entry.cpp, kernel/eir/system/dtb/discovery.cpp, kernel/klibc/elf.h
Make the virt target PIE (otherwise it is too annoying to use it on multiple SoCs with different load addresses). Also properly integrate DTB memory parsing code that we wrote when initially starting the RISC-V port a few years ago.
=> eir: Make the virt target work on RISC-V

kernel/common/riscv/csr.hpp, kernel/eir/arch/riscv/arch.cpp, kernel/eir/arch/riscv/cpu.cpp, kernel/eir/arch/riscv/eir-internal/arch/riscv.hpp, kernel/klibc/eir/interface.hpp, kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/system.cpp, kernel/thor/arch/riscv/thor-internal/arch/system.hpp, kernel/thor/arch/riscv/timer.cpp
The Sstc extension allows S-mode to set a timer comparison CSR. This avoids the need to call into SBI. In fact, some boards implement Sstc but not the TIME extension for SBI.
=> thor: Support Sstc timer on RISC-V

kernel/eir/arch/riscv/cpu.cpp, kernel/klibc/eir/interface.hpp
This adds parsing of `riscv,isa`. While the `riscv,isa-base` and `riscv,isa-extensions` properties that we already handle should be preferred over `riscv,isa`, lots of DTs still use the less accurate `riscv,isa`.
=> kernel/eir: Parse riscv,isa DT property

kernel/eir/generic/main.cpp, kernel/klibc/eir/interface.hpp, kernel/thor/arch/arm/cpu.cpp, kernel/thor/arch/arm/link.x, kernel/thor/arch/arm/smp.cpp, kernel/thor/arch/arm/thor-internal/arch/cpu.hpp, kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/link.x, kernel/thor/arch/x86/cpu.cpp, kernel/thor/arch/x86/link.x, kernel/thor/generic/cpu-data.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/thor-internal/cpu-data.hpp, kernel/thor/meson.build
With this mechanism new code (both generic and architecture-specific) can add new CPU-local variables by just doing:
extern PerCpu\<MyType\> myLocal;
THOR_DEFINE_PERCPU(myLocal);
instead of having to add the variable as a member to either PlatformCpuData or CpuData.
This should hopefully help untangle the header dependencies for cpu-data.hpp a bit, and help move some large stuff away from the head of CpuData (e.g. GDT and IDT on x86_64).
CpuData (and {Assembly,Platform}CpuData) is still kept around for stuff we want at/near the start of the CPU-local data (e.g. the self pointer, stuff accessed from assembly code, hot members). But for most things, the new mechanism should be used.
=> thor: Add a generic mechanism for declaring CPU-local variables

kernel/common/riscv/sbi.hpp, kernel/eir/protos/limine/entry.cpp, kernel/eir/protos/limine/limine.h, kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/entry.S, kernel/thor/arch/riscv/meson.build, kernel/thor/arch/riscv/paging.cpp, kernel/thor/arch/riscv/smp.cpp, kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp
This PR boots APs on RISC-V (which is actually more pleasant than on x86 and ARM since SBI allows us to pass an opaque pointer to the entry stub).
=> thor: Boot APs on RISC-V

kernel/thor/arch/riscv/cpu.cpp, kernel/thor/arch/riscv/paging.cpp, kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp, kernel/thor/generic/hel.cpp
After this PR, only ASID-related `thor-internal/arch/` functions are still unimplemented on RISC-V.
=> thor: Implement most remaining RISC-V stubs

kernel/thor/arch/arm/meson.build, kernel/thor/generic/main.cpp, kernel/thor/generic/thor-internal/mbus.hpp, kernel/thor/system/dtb/dtb_discover.cpp, kernel/thor/system/dtb/thor-internal/dtb/dtb.hpp, protocols/hw/hw.bragi, protocols/hw/include/protocols/hw/client.hpp, protocols/hw/src/client.cpp
Publish dtb nodes to mbus. This is a draft because I am not sure if the mbus refactor should get merged first and also it would be nice to get #617 merged so AccessIrqRequest could be supported too.
=> kernel/thor: Publish dtb nodes to mbus

kernel/thor/generic/main.cpp, kernel/thor/system/dtb/dtb_discover.cpp, kernel/thor/system/dtb/thor-internal/dtb/dtb.hpp, protocols/hw/hw.bragi, protocols/hw/include/protocols/hw/client.hpp, protocols/hw/src/client.cpp
Add `drvcore.mbus-parent` property to the mbus dt nodes and rename Dtb -> Dt.
=> kernel/thor: Add parent to mbus dtb nodes

kernel/thor/system/acpi/acpi.cpp, kernel/thor/system/acpi/battery.cpp, kernel/thor/system/acpi/madt.cpp, kernel/thor/system/acpi/ps2.cpp, kernel/thor/system/acpi/thor-internal/acpi/acpi.hpp
Calling uACPI functions from work queues leads to issues like entering a work queue recursively.
=> thor: Avoid calling uACPI functions while not on a fiber

kernel/thor/arch/arm/ints.cpp, kernel/thor/arch/riscv/plic.cpp, kernel/thor/arch/riscv/thor-internal/arch/ints.hpp, kernel/thor/arch/riscv/thor-internal/arch/system.hpp, kernel/thor/arch/riscv/trap.cpp, kernel/thor/arch/x86/ints.cpp, kernel/thor/generic/irq.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/thor-internal/irq.hpp
Refactor `handleIrq()` to directly take a `IrqPin *` and remove the use of `globalIrqSlots` on RISC-V.
=> thor: Rework globalIrqSlots to remove them on non-x86

kernel/thor/generic/main.cpp, kernel/thor/generic/schedule.cpp, kernel/thor/generic/thor-internal/schedule.hpp, kernel/thor/generic/thread.cpp
Avoid the need to self IPI when resuming threads. We previously used self IPIs to exit the idle task when a thread was resumed from thread observation handlers in the kernel. Avoid entering the idle task if any observation handlers are enqueued.
=> thor: Reduce the number of self IPIs to ping the scheduler

kernel/thor/arch/arm/ints.cpp, kernel/thor/arch/arm/timer.cpp, kernel/thor/arch/riscv/paging.cpp, kernel/thor/arch/riscv/timer.cpp, kernel/thor/arch/riscv/trap.cpp, kernel/thor/arch/x86/ints.cpp, kernel/thor/arch/x86/pic.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/schedule.cpp, kernel/thor/generic/thor-internal/schedule.hpp, kernel/thor/system/pci/pci_dtb.cpp
After removing self IPIs when resuming tasks, we were missing checks for preemption in some code paths (in particular, IPI exit code paths).
Add the missing checks. Also add a mechanism to determine whether calling into `handlePreemption()` is necessary or not.
Finally, we fix some issues that complicate testing the PR (namely a fix for aarch64 PCI enumeration + RISC-V paging).
=> thor: Fix missing checks for preemption on all archs

posix/subsystem/src/tmp_fs.cpp
Systemd choked on this, and I have my doubts if that assert is even needed. Also, 0 links makes no sense, hardcoding to 1 sounds better (but implementing it properly is of course even better).
=> posix: Assorted fixes for tmpfs MemoryFile

drivers/block/nvme/src/controller.cpp, drivers/block/nvme/src/controller.hpp
The NVMe specification requires a `Set Features` command with Feature ID 0x07 (Number of Queues) to be issued before setting up I/O queues. This has been the case since version 1.0 of the spec. For reference, see section 7.6.1 "Initialization" of the NVMe 1.3d spec (p. 115), point 8.
=> drivers/nvme: request a number of I/O queues as mandated by spec

kernel/thor/arch/arm/ints.cpp, kernel/thor/arch/riscv/trap.cpp, kernel/thor/arch/x86/ints.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/schedule.cpp, kernel/thor/generic/thor-internal/schedule.hpp, kernel/thor/generic/thor-internal/thread.hpp, kernel/thor/generic/thread.cpp
Fix remaining TODOs after the removal of self-ping-IPIs. This fixes a potential hangs if there is only a single runnable thread (such that we do not arm the preemption tick) and that thread never yields after waking up other threads.
=> thor: Check preemption from faults and syscalls

posix/init/src/stage1.cpp, posix/subsystem/src/netlink/nl-socket.cpp, posix/subsystem/src/netlink/nl-socket.hpp, posix/subsystem/src/requests.cpp, posix/subsystem/src/un-socket.cpp
This PR adds the necessary infrastructure to stage1 to support booting with systemd. It also contains a quick fix for SO_PASSCREDS handling on unix sockets and an addition to getsockopt for netlink sockets. This PR is made to facilitate debugging, and does not conclude the work to get systemd working on Managarm.
=> Initial systemd boot support

kernel/thor/generic/kernel-log.cpp, kernel/thor/generic/main.cpp, kernel/thor/generic/thor-internal/kernel-log.hpp
This makes the global log buffer (which ultimately feeds into `dmesg`) available early during boot (= immediately after entering `thorMain()`).
=> thor: Make global log ring available early

posix/init/src/stage1.cpp
This eases debugging systemd on Managarm.
=> posix/init: Make systemd boot be configurable from the kernel commandline

meson.build, meson_options.txt, posix/subsystem/src/requests.cpp, testsuites/posix-tests/src/faults.cpp, testsuites/posix-tests/src/inotify.cpp, testsuites/posix-tests/src/mmap.cpp, testsuites/posix-tests/src/parent-dead-signal.cpp, testsuites/posix-tests/src/sigaltstack.cpp, testsuites/posix-tests/src/signal.cpp
This enables us to build the POSIX testsuite on Linux to allow for easier comparisons to Managarm.
Merge together with https://github.com/managarm/bootstrap-managarm/pull/458.
=> posix-tests: Enable build on Linux and fix/workaround various bugs

posix/subsystem/src/observations.cpp
Fixes bogus errors when calling `pthread_kill`.
=> posix: Set SIG_KILL return value to 0

kernel/thor/generic/address-space.cpp, kernel/thor/generic/memory-view.cpp, kernel/thor/generic/thor-internal/memory-view.hpp
While the current hierarchical implementation of CoW does not require a lot of work in `fork()`, it adds a lot of memory footprint and it can potentially cause OOM in unexpected ways (e.g., if a process forks repeatedly). Switch to a non-hierarchical implementation that just keeps per-page refcounts.
=> thor: Make copy-on-write non-hierarchical

meson.build, utils/wait-for-devices/meson.build, utils/wait-for-devices/src/main.cpp
In contrast to Linux, not all devices are already up when userspace boots. In particular, from the perspective of userspace devices such as the graphics card or USB HID devices are hotplugged at runtime. Add a `wait-for-devices` utility that the init system can use to wait until certain devices are available.
=> wait-for-devices: Add utility to wait for udev devices

posix/subsystem/src/cgroupfs.hpp, posix/subsystem/src/device.cpp, posix/subsystem/src/device.hpp, posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/extern_fs.hpp, posix/subsystem/src/file.hpp, posix/subsystem/src/fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp, posix/subsystem/src/pts.cpp, posix/subsystem/src/requests.cpp, posix/subsystem/src/subsystem/block.cpp, posix/subsystem/src/subsystem/generic.cpp, posix/subsystem/src/sysfs.hpp, posix/subsystem/src/tmp_fs.cpp, posix/subsystem/src/tmp_fs.hpp, posix/subsystem/src/vfs.cpp, posix/subsystem/src/vfs.hpp, protocols/posix/posix.bragi
Implements `/proc/mounts` and `/proc/[pid]/mountinfo`, which should allow for running `mount` on managarm.
=> Mount information in procfs

kernel/common/riscv/csr.hpp, kernel/thor/arch/riscv/aplic.cpp, kernel/thor/arch/riscv/thor-internal/arch/trap.hpp, kernel/thor/arch/riscv/trap.cpp, kernel/thor/system/dtb/thor-internal/dtb/dtb.hpp
Add support for the IMISC controller. The IMSIC is an MSI-based interrupt controller that is directly integrated into the CPU.
To support non-MSI interrupts, the APLIC can be programmed to convert non-MSI interrupts to MSIs that are forwarded to the IMSIC.
=> thor: Support IMSIC interrupt controller on RISC-V

posix/subsystem/src/fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/inotify.cpp, posix/subsystem/src/inotify.hpp, posix/subsystem/src/requests.cpp, posix/subsystem/src/tmp_fs.cpp, protocols/posix/posix.bragi, testsuites/posix-tests/src/inotify.cpp
More systemd bugfixes! This time adding support for `IN_ISDIR`, supporting blocking reads and fixing a bug where we potentially try to use the front of an empty queue.
=> inotify: Various fixes for inotify support

kernel/thor/arch/arm/gic_v2.cpp, kernel/thor/arch/arm/gic_v3.cpp, kernel/thor/arch/arm/thor-internal/arch/gic.hpp, kernel/thor/arch/arm/thor-internal/arch/gic_v2.hpp, kernel/thor/arch/arm/thor-internal/arch/gic_v3.hpp, kernel/thor/arch/riscv/aplic.cpp, kernel/thor/arch/riscv/plic.cpp, kernel/thor/arch/x86/pic.cpp, kernel/thor/generic/irq.cpp, kernel/thor/generic/thor-internal/irq.hpp
This makes it easier to support the PLIC (and in a future PR, also the IMSIC). In particular, level-triggered PLIC interrupts need to be completed when they exit service (and not when the synchronous IRQ handler completes).
=> thor: Rework IrqStrategy to make IrqPin logic more flexible

posix/subsystem/src/file.cpp, posix/subsystem/src/fs.cpp, posix/subsystem/src/fs.hpp, posix/subsystem/src/procfs.cpp
This avoids crashes in posix-subsystem that can be triggered from user code.
=> posix: Remove various exceptions, replace by error returns

hel/include/hel-syscalls.h, hel/include/hel.h, kernel/thor/generic/hel.cpp, kernel/thor/generic/main.cpp
This makes it possible to include the hel headers from C source files. Also added a `kHelActionNone` constant because there wasn't one and it's useful for my WIP Rust bindings.
=> hel: Fix argument types and parameter qualifiers

kernel/thor/generic/gdbserver.cpp, posix/subsystem/src/gdbserver.cpp
Fix the aarch64 register sizes in thor gdbserver and add support for aarch64 register read in the posix one.
=> Fix aarch64 gdbservers

drivers/libblockfs/include/scsi.hpp, drivers/libblockfs/meson.build, drivers/libblockfs/src/scsi.cpp, drivers/usb/devices/storage/src/main.cpp, drivers/usb/devices/storage/src/storage.hpp
Add an abstraction for scsi and use it for usb-storage. Also fill the parent property of BlockDevice to fix a regression introduced in 9760ccf552b7e96bec7515f6fb5fe545b77fe733 where if the device would have no parent it would create the device link in the subsystem's sysfs twice resulting in an assert fail.
=> Add scsi abstraction

core/drm/src/core.cpp, core/drm/src/ioctl.cpp, core/lib/cmdline.cpp, core/lib/kernel-logs.cpp, drivers/clocktracker/src/main.cpp, drivers/kernletcc/src/main.cpp, drivers/libevbackend/src/libevbackend.cpp, drivers/nic/usb_net/src/usb-mbim.cpp, drivers/usb/devices/serial/src/main.cpp, hel/include/helix/ipc.hpp, posix/subsystem/src/device.cpp, posix/subsystem/src/devices/kmsg.cpp, posix/subsystem/src/extern_fs.cpp, posix/subsystem/src/fifo.cpp, posix/subsystem/src/file.cpp, posix/subsystem/src/inotify.cpp, posix/subsystem/src/main.cpp, posix/subsystem/src/pts.cpp, posix/subsystem/src/requests.cpp, posix/subsystem/src/un-socket.cpp, protocols/fs/src/client.cpp, protocols/fs/src/server.cpp, protocols/mbus/src/client_ng.cpp, protocols/usb/src/client.cpp, protocols/usb/src/server.cpp, servers/netserver/src/ip/tcp4.cpp, servers/netserver/src/main.cpp, servers/netserver/src/netlink/netlink.cpp
This removes all uses of `helix::action` and removes it from the headers. The last commit came to be by checking all instances of recvInline and aggressively resetting the result to avoid a full queue.
=> Nvidia driver, part 2: fix IPC issues

posix/subsystem/src/observations.cpp, posix/subsystem/src/process.cpp
This is necessary due to the changes to that function that allow passing multiple tokens.
=> posix: explicitly construct tokens for async::suspend_indefinitely

drivers/libblockfs/src/ext2fs.cpp, drivers/libblockfs/src/gpt.cpp, drivers/libblockfs/src/gpt.hpp, drivers/libblockfs/src/raw.cpp
Add support for reading the gpt on devices where the device block size doesn't match what the gpt was created with by probing for the gpt at different locations for the common block sizes and fix some hardcoded usages of 512 byte block size. This is useful for an example to boot a Managarm image created with the typical 512 byte block size using UFS which only supports hardware block sizes greater than 4kb.
=> drivers/libblockfs: Support non-native gpt block sizes

drivers/nic/freebsd-e1000/meson.build
Depends on managarm/bootstrap-managarm#543.
=> drivers/freebsd-e1000: use pkgconfig instead of meson subprojects

posix/subsystem/src/file.hpp, posix/subsystem/src/main.cpp, posix/subsystem/src/process.cpp, posix/subsystem/src/procfs.cpp, posix/subsystem/src/procfs.hpp, posix/subsystem/src/requests.cpp, posix/subsystem/src/util.cpp, protocols/fs/fs.bragi, protocols/fs/include/protocols/fs/common.hpp, testsuites/posix-tests/meson.build, testsuites/posix-tests/src/procfs.cpp
This fixes the inconsistent boot failures that dereferenced a pointer to `0x40`.
=> posix: allow error returns for procfs attribute reads

kernel/thor/generic/servers.cpp, posix/subsystem/src/exec.cpp, tools/gen-initrd.py
This change is needed because we're switching the name of the dynamic linker. Additional PRs to mlibc, gcc, llvm and bootstrap will come later, therefore currently this is a draft.
=> tools: Update gen-initrd with the new name of the dynamic linker

kernel/eir/arch/arm/platform/raspi4/raspi4.cpp, kernel/eir/arch/arm/platform/virt/virt.cpp, kernel/eir/arch/riscv/platform/allwinner-d1/early-log.cpp, kernel/eir/arch/riscv/platform/virt/early-log.cpp, kernel/eir/arch/x86/arch.cpp, kernel/eir/generic/eir-internal/arch.hpp, kernel/eir/protos/limine/entry.cpp, kernel/eir/protos/multiboot2/multiboot2.cpp, kernel/eir/protos/uefi/entry.cpp, kernel/eir/protos/uefi/meson.build
`-lld-allow-duplicate-weak` causes lld to select on of the definitions for each weak symbol. However, it does not select a non-null definition over a null definition which makes it unsuitable for our purposes.
Drop the flag such that we get compile time errors on weak symbols.
Depends on https://github.com/managarm/frigg/pull/94
=> eir: Drop -lld-allow-duplicate-weak

kernel/eir/arch/arm/generic.cpp, kernel/eir/arch/arm/platform/raspi4/raspi4.cpp, kernel/eir/arch/x86/generic32_link.x, kernel/eir/arch/x86/generic64_link.x, kernel/eir/generic/debug.cpp, kernel/eir/generic/eir-internal/debug.hpp, kernel/eir/generic/eir-internal/framebuffer.hpp, kernel/eir/generic/eir-internal/generic.hpp, kernel/eir/generic/eir-internal/main.hpp, kernel/eir/generic/framebuffer.cpp, kernel/eir/generic/main-function.cpp, kernel/eir/meson.build, kernel/eir/protos/limine/entry.cpp, kernel/eir/protos/multiboot2/multiboot2.cpp, kernel/eir/protos/uefi/entry.cpp, kernel/eir/system/acpi/acpi.cpp
This moves the boot framebuffer handling to its own file and it fixes a few small issues (in MB2 and Limine protocols).
=> eir: Handle boot framebuffer consistently on all boot protocols

kernel/eir/arch/arm/platform/raspi4/raspi4.cpp, kernel/eir/generic/main.cpp, kernel/eir/system/acpi/console.cpp, kernel/eir/system/dtb/discovery.cpp, kernel/eir/system/uart/eir-internal/uart/ns16550.hpp, kernel/eir/system/uart/eir-internal/uart/pl011.hpp, kernel/eir/system/uart/eir-internal/uart/uart.hpp, kernel/eir/system/uart/uart.cpp, kernel/klibc/eir/interface.hpp, kernel/thor/arch/arm/debug.cpp
The move to `eir-linux` temporarily dropped the code to set the boot UART tag. Re-introduce code to do this but make it more generic this time (such that it works for DT and ACPI provided UARTs).
=> eir: Let Eir's UART subsystem pass boot UART tag

drivers/usb/hcds/uhci/src/main.cpp, protocols/usb/src/server.cpp
This makes UHCI work in QEMU again; tested with QEMU's keyboard and tablet devices in weston and kmscon using evtest.
=> UHCI fixes
