- README.md
- core/drm/include/core/drm/core.hpp
- core/drm/src/core.cpp
- drivers/gfx/vmware/src/main.cpp
- drivers/gfx/vmware/src/spec.hpp
- drivers/gfx/vmware/src/vmware.hpp
This pull request implements functionality mentioned in issue #25.
> Implement accelerated cursors.

- core/drm/src/core.cpp
Related to https://github.com/managarm/mlibc/pull/9
> core/drm: properly return errors when handling DRM_IOCTL_MODE_CURSOR

- frigg/include/frigg/arch_x86/machine.hpp
- kernel/eir/load.S
- kernel/eir/main.cpp
- kernel/eir/main.hpp
- kernel/eir/meson.build
- kernel/eir/multiboot1/multiboot1.S
- kernel/eir/multiboot1/multiboot1.cpp
frigg: Add constants for PAT detection
> eir: Generalize booting

- meson.build
- utils/lsmbus/meson.build
- utils/lsmbus/src/main.cpp
caveat: currently unable to end itself
> utils: add lsmbus: a tool to enumerate mbus

- bragi/proto/fs.proto
- bragi/proto/posix.proto
- posix/subsystem/src/file.cpp
- posix/subsystem/src/file.hpp
- posix/subsystem/src/main.cpp
- posix/subsystem/src/nl-socket.cpp
- posix/subsystem/src/un-socket.cpp
- protocols/fs/include/protocols/fs/common.hpp
- protocols/fs/include/protocols/fs/server.hpp
- protocols/fs/src/server.cpp
related pr: https://github.com/managarm/mlibc/pull/24
> protocols: migrate sendmsg/recvmsg to fs

- drivers/libblockfs/src/libblockfs.cpp
- posix/subsystem/src/extern_fs.cpp
- protocols/fs/fs.proto
These commits implement rename in posix and underlying ext2 support.
This should fix #71
> posix: Implemented rename

- posix/subsystem/src/main.cpp
- protocols/posix/posix.proto
This commit requires a header change in mlibc, this introduces AT_EACCESS
> posix: Implemented ACCESSAT

- posix/subsystem/src/extern_fs.cpp
Fixed file modified and creation time and actually pass the file mode to mlibc.
> posix/extern_fs: small fixes to getStats()

- posix/subsystem/src/file.cpp
- posix/subsystem/src/file.hpp
- protocols/fs/include/protocols/fs/server.hpp
- protocols/fs/src/server.cpp
This is the managarm counterpart of managarm/mlibc#108
> posix: Stubbed File::listen() to satisfy udevd after an change in mlibc

- posix/subsystem/src/fs.cpp
- posix/subsystem/src/main.cpp
- posix/subsystem/src/pts.cpp
- posix/subsystem/src/vfs.cpp
- protocols/posix/posix.bragi
posix: Hande getLink unimplemented gracefully
posix: Handle illegal FD in EPOLL_DELETE gracefully
posix: Handle unlinking the root
posix: Handle writes of size 0 in pts
> posix: Various improvements

- posix/init/src/stage2.cpp
- posix/subsystem/src/fs.cpp
- posix/subsystem/src/fs.hpp
- posix/subsystem/src/tmp_fs.cpp
- posix/subsystem/src/un-socket.cpp
This PR adds basic support for abstract sockets in bind, as required by `weston`'s `xwayland` module
> posix: Implement changes required for xwayland support in weston

- docs/src/SUMMARY.md
- docs/src/design/drivers/index.md
- docs/src/design/drivers/libblockfs/index.md
- docs/src/design/libblockfs/index.md
- docs/src/design/mbus/index.md
- docs/src/design/posix/index.md
- docs/src/getting-started/supported/package_index.md
I've added some documentation about the posix-subsystem and libblockfs, updated the package list, fixed a typo and included a link to the source code of mbus
> docs: Add more docs

- protocols/fs/src/server.cpp
This PR turns assertions into error responses in the fs code.
This PR closes #209
> protocols/fs: Change assertions into error returns

- posix/subsystem/src/exec.cpp
This PR fixes a trigger of #224, but doesn't address the primary cause of this issue
> posix: Fix broken conditional in execute()

- posix/subsystem/src/main.cpp
> posix: Fix bug in the GETCWD request

- posix/subsystem/src/process.cpp
This PR fixes a signal handling bug found by the posix_spawn implementation found in managarm/mlibc#201.
This PR is not really blocked on managarm/mlibc#201, but should be merged together with it to avoid breaking changes
> posix: Fix an off by one bug in the signal handling code

- posix/subsystem/src/file.cpp
This PR fixes certain applications crashing on calling ioctl on a writer side fifo.
After this, one should merge managarm/mlibc#224
> posix: Mark all ioctls on writer side fifo's as invalid

- posix/subsystem/src/main.cpp
- posix/subsystem/src/process.cpp
This PR fixes more off-by-one bugs in the signal handling code. It also adds error handling for invalid signal numbers in the `SIG_ACTION` request.
After this PR is merged, managarm/mlibc#228 should be merged
> Fix off-by-one bugs in signal handling

- posix/subsystem/src/process.cpp
> posix: Handle SIG_IGN

- kernel/thor/generic/gdbserver.cpp
- kernel/thor/generic/service.cpp
- kernel/thor/generic/thor-internal/gdbserver.hpp
- kernel/thor/meson.build
We add a GDB server to `thor`. Whenever a server dies with a panic or segfault, we launch the server over the standard PC uart.
> thor: Add GDB server over serial I/O

- posix/subsystem/src/epoll.cpp
- posix/subsystem/src/epoll.hpp
- posix/subsystem/src/main.cpp
This allows Rust programs to run.
Note: I did not write this code, avdgrinten did :)
> posix: Fix poll/epoll FD duplication checks

- docs/src/SUMMARY.md
- docs/src/building.md
- docs/src/contributing/coding-style.md
- docs/src/contributing/commit-messages.md
- docs/src/contributing/communication.md
- docs/src/contributing/contributing.md
- docs/src/contributing/direct/direct.md
- docs/src/contributing/overview.md
- docs/src/getting-started/index.md
- docs/src/getting-started/supported/index.md
- docs/src/getting-started/supported/package_index.md
- docs/src/getting-started/trying-out.md
This PR is a work in progress and aims to update the available documentation. Current focus lies on how to contribute to the project and documenting more of managarm's internal workings.
> Updated documentation

- drivers/libblockfs/src/ext2fs.cpp
> drivers/libblockfs: Enlarge directory in link()

- drivers/libblockfs/src/libblockfs.cpp
> drivers/libblockfs: Fix reading long symlinks on ext2 filesystems

- docs/src/building.md
> docs: Add information on image updating methods

- docs/src/SUMMARY.md
- docs/src/contributing/xbstrap.md
Add a short page to document basic `xbstrap` subcommands.
> docs: Document xbstrap workflow

- drivers/kbd/src/main.cpp
Resolves issue #75 with function and numpad keys not working properly.
> drivers: fix ps2 function and numpad keys

- docs/src/SUMMARY.md
- docs/src/building/updating.md
Another PR towards more complete documentation for contributors and people who want to build Managarm from source.
> docs: Document how to update packages

- docs/src/SUMMARY.md
- docs/src/impl-notes/drivers/index.md
- docs/src/impl-notes/drivers/irqs.md
This PR adds documentation on how drivers need to behave for IRQ handling to work correctly.
> Document IRQ handling from driver's point of view

- core/drm/src/core.cpp
- drivers/libevbackend/src/libevbackend.cpp
- posix/subsystem/src/file.cpp
- protocols/fs/src/server.cpp
This PR dismisses ioctl requests in posix if the device does not implement any ioctl functionality.
> Dismiss unimplemented ioctls

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- README.md
- docs/src/building/index.md
- docs/src/getting-started/supported/index.md
- docs/src/getting-started/supported/package_index.md
- docs/src/getting-started/trying-out.md
> workflows: refactor urls post-migration

- kernel/thor/arch/arm/thor-internal/arch/paging.hpp
- kernel/thor/arch/x86/thor-internal/arch/paging.hpp
- kernel/thor/generic/address-space.cpp
- posix/subsystem/src/main.cpp
- posix/subsystem/src/process.cpp
- posix/subsystem/src/process.hpp
- testsuites/posix-tests/meson.build
- testsuites/posix-tests/src/sigaltstack.cpp
This pull request does not include the fixes for mmap/munmap/mprotect.
Depends on managarm/mlibc#298.
> Improvements for QEMU

- .mailmap
this also applies to other repos, if we conclude it's a fine addition
> meta: add git mailmap for changed emails

- posix/subsystem/src/exec.cpp
- posix/subsystem/src/exec.hpp
- posix/subsystem/src/extern_fs.cpp
- posix/subsystem/src/fs.cpp
- posix/subsystem/src/fs.hpp
- posix/subsystem/src/gdbserver.cpp
- posix/subsystem/src/main.cpp
- posix/subsystem/src/process.cpp
- posix/subsystem/src/process.hpp
- posix/subsystem/src/procfs.cpp
- posix/subsystem/src/procfs.hpp
- posix/subsystem/src/sysfs.cpp
- posix/subsystem/src/sysfs.hpp
- posix/subsystem/src/tmp_fs.cpp
- posix/subsystem/src/un-socket.cpp
- posix/subsystem/src/vfs.cpp
- posix/subsystem/src/vfs.hpp
Added ``/proc/self``, ``/proc/*/exe`` and ``/proc/*/maps``.
> Procfs improvements

- protocols/posix/posix.bragi
> posix: Fix a duplicated bragi message ID

- docs/src/SUMMARY.md
- docs/src/contributing/lsp.md
Depends on https://github.com/managarm/bootstrap-managarm/pull/170 and cbuildrt and xbstrap releases.
> docbook: add LSP instructions

- drivers/block/ahci/src/command.cpp
- drivers/block/ahci/src/controller.cpp
- drivers/block/ahci/src/controller.hpp
- drivers/block/ahci/src/main.cpp
- drivers/block/ahci/src/port.cpp
- drivers/block/ahci/src/port.hpp
- drivers/block/ahci/src/spec.hpp
Fixes various AHCI issues to allow us to run on real hardware. Fixes managarm#323.
Draft until I can fix all the remaining problems.
> block/ahci: Various fixes

- meson.build
- subprojects/cxxshim.wrap
- subprojects/frigg.wrap
- tools/pb2frigg/meson.build
Blocked on https://github.com/managarm/frigg/pull/28 and https://github.com/managarm/bootstrap-managarm/pull/182
> meson: use frigg and cxxshim from pkg-config

- kernel/thor/generic/debug.cpp
- kernel/thor/generic/hel.cpp
- kernel/thor/generic/thor-internal/debug.hpp
- kernel/thor/system/framebuffer/boot-screen.cpp
This should make some assertion failures more readable.
> kernel: increase log buffer from 100 to 256

- kernel/thor/generic/service.cpp
- posix/subsystem/src/main.cpp
- protocols/posix/include/protocols/posix/supercalls.hpp
- protocols/posix/meson.build
- protocols/posix/posix.bragi
Also convert GetPid request to bragi
> posix: clean up supercalls and turn GetTid into one

- kernel/thor/arch/x86/meson.build
- kernel/thor/generic/hel.cpp
- kernel/thor/generic/io.cpp
- kernel/thor/generic/kernlet.cpp
- kernel/thor/system/acpi/glue.cpp
> thor: substitute __x86_64__ for THOR_ARCH_SUPPORTS_PIO

- kernel/common/physical-buddy.hpp
- kernel/eir/generic/main.cpp
- posix/subsystem/src/main.cpp
- posix/subsystem/src/process.cpp
- posix/subsystem/src/pts.cpp
> Misc. fixes and SIGWINCH support.

- hel/include/hel.h
- kernel/common/x86/machine.hpp
- kernel/thor/arch/x86/cpu.cpp
- kernel/thor/arch/x86/ept.cpp
- kernel/thor/arch/x86/meson.build
- kernel/thor/arch/x86/npt.cpp
- kernel/thor/arch/x86/svm.cpp
- kernel/thor/arch/x86/svm_stubs.S
- kernel/thor/arch/x86/thor-internal/arch/cpu.hpp
- kernel/thor/arch/x86/thor-internal/arch/npt.hpp
- kernel/thor/arch/x86/thor-internal/arch/svm.hpp
- kernel/thor/arch/x86/thor-internal/arch/vmx.hpp
- kernel/thor/arch/x86/vmx.cpp
- kernel/thor/arch/x86/vmx_stubs.S
- kernel/thor/generic/address-space.cpp
- kernel/thor/generic/hel.cpp
- meson.build
- testsuites/virt-test/main.cpp
- testsuites/virt-test/meson.build
> thor/svm: Implement basic SVM support + virtualization test

- core/drm/src/core.cpp
- drivers/gfx/bochs/src/main.cpp
- drivers/gfx/plainfb/src/main.cpp
- drivers/gfx/virtio/src/main.cpp
- drivers/libterminal/include/libterminal.hpp
- drivers/usb/devices/hid/src/main.cpp
- drivers/usb/devices/storage/src/main.cpp
- kernel/thor/generic/thor-internal/coroutine.hpp
- kernel/thor/meson.build
- meson.build
- posix/subsystem/src/devices/full.cpp
- posix/subsystem/src/devices/helout.cpp
- posix/subsystem/src/devices/null.cpp
- posix/subsystem/src/devices/random.cpp
- posix/subsystem/src/devices/urandom.cpp
- posix/subsystem/src/devices/zero.cpp
- posix/subsystem/src/fifo.cpp
- posix/subsystem/src/vfs.cpp
Depends on managarm/cxxshim#10 and managarm/libasync#16.
> Switch from `<experimental/coroutine>` to `<coroutine>`

- drivers/kbd/src/main.cpp
When booting on my ThinkPad Yoga 370, booting failed due to multiple failures that this commit addressed. Firstly, the identifier for the keyboard was 0xAB84, which has been whitelisted. Secondly, if setting the scancode fails (which happens on that machine), we just skip it as we can assume that scancode 2 is the default.
For good measure, we ensure that the keyboard is not disabled and that scancode set translation from set 2 to set 1 is not enabled in the PS/2 controller.
> drivers/kbd: allow for skipping scancode set selection

- posix/subsystem/src/process.cpp
- posix/subsystem/src/process.hpp
- posix/subsystem/src/procfs.cpp
Addresses concerns raised in #496
> Enhancements to /proc/[pid]/comm

- core/drm/include/core/drm/core.hpp
- core/drm/src/ioctl.cpp
- drivers/libblockfs/src/libblockfs.cpp
- drivers/libevbackend/include/libevbackend.hpp
- drivers/libevbackend/src/libevbackend.cpp
- posix/subsystem/src/fifo.cpp
- posix/subsystem/src/file.cpp
- posix/subsystem/src/file.hpp
- posix/subsystem/src/pts.cpp
- posix/subsystem/src/subsystem/input.cpp
- posix/subsystem/src/un-socket.cpp
- protocols/fs/fs.bragi
- protocols/fs/include/protocols/fs/server.hpp
- protocols/fs/src/server.cpp
> protocols/fs: break out ioctls into their own message

- kernel/thor/generic/thor-internal/address-space.hpp
As discussed on Discord, the assert is not correct, and should be changed to an if statement.
> thor: Remove a not needed assert in remapPresentPagesByCursor

- posix/subsystem/src/nl-socket.cpp
WebKitGTK ran into these asserts, but commenting them out broke nothing. Seems to me that some if not all of these asserts are thus either wrong or not needed.
I'm not sure if this is correct, so someone with knowledge about this should review this.
> posix: Remove several netlink asserts

- kernel/thor/system/pci/pci_discover.cpp
This prevents devices from spuriously decoding addresses leading to invalid reads. This tends to happen mostly with PCI passthrough devices in my experience.
> thor: disable I/O and memory decode before reading BAR length

- drivers/usb/devices/hid/src/main.cpp
- drivers/usb/hcds/ehci/src/ehci.hpp
- drivers/usb/hcds/ehci/src/main.cpp
> drivers/ehci: fix EHCI and HID issues

- core/drm/include/core/drm/device.hpp
- core/drm/include/core/drm/mode-object.hpp
- core/drm/include/core/drm/property.hpp
- core/drm/src/device.cpp
- core/drm/src/ioctl.cpp
- core/drm/src/mode-object.cpp
- core/drm/src/property.cpp
- drivers/gfx/bochs/src/bochs.hpp
- drivers/gfx/bochs/src/main.cpp
- drivers/gfx/plainfb/src/main.cpp
- drivers/gfx/plainfb/src/plainfb.hpp
- drivers/gfx/virtio/src/main.cpp
- drivers/gfx/virtio/src/virtio.hpp
- drivers/gfx/vmware/src/main.cpp
- drivers/gfx/vmware/src/vmware.hpp
- posix/subsystem/src/process.cpp
- protocols/fs/fs.bragi
Depends on #540 (and includes the commits for easier testing).
> DRM fixes in preparation for virtio-gpu

- posix/subsystem/src/fifo.cpp
Fixes node.js when running scripts.
> posix: Handle closed fifo files while waiting in poll

- posix/subsystem/src/exec.cpp
The old checks check for misalignment of p_vaddr and p_offset individually, when the only requirement is that they are both equally misaligned.
> posix: Properly handle misaligned elf segments

- posix/subsystem/src/requests.cpp
Depends on https://github.com/managarm/mlibc/pull/898
> posix: Fail on misaligned mmap offset

- kernel/thor/generic/address-space.cpp
- testsuites/posix-tests/src/mmap.cpp
Should solve firefox for @Dennisbonke
> Fix mprotect and add a test case

- drivers/libblockfs/src/ext2fs.hpp
- drivers/libblockfs/src/libblockfs.cpp
- posix/subsystem/src/extern_fs.cpp
- posix/subsystem/src/file.hpp
- posix/subsystem/src/fs.hpp
- posix/subsystem/src/requests.cpp
- protocols/fs/fs.bragi
- protocols/fs/include/protocols/fs/server.hpp
- protocols/fs/src/server.cpp
- protocols/posix/posix.bragi
This PR implements handling for O_APPEND.
> fs: Implement O_APPEND for ext2

- kernel/thor/generic/service.cpp
This will help us eventually moving over to the linux abi, if we desire to do so. It also improves readability.
> thor: Use the mmap constants from mlibc

- kernel/thor/generic/address-space.cpp
> thor: avoid deep recursion when destroying CowChain

- kernel/thor/generic/gdbserver.cpp
- posix/subsystem/src/gdbserver.cpp
We've already done this for posix, let's do it for the kernel too.
> thor: Don't launch gdbserver more than once if servers die

- core/drm/include/core/drm/core.hpp
- core/drm/include/core/drm/device.hpp
- core/drm/include/core/drm/mode-object.hpp
- core/drm/include/core/drm/property.hpp
- core/drm/meson.build
- core/drm/src/core.cpp
- core/drm/src/device.cpp
- core/drm/src/fourcc.cpp
- core/drm/src/ioctl.cpp
- core/drm/src/mode-object.cpp
- core/drm/src/property.cpp
- drivers/gfx/bochs/src/bochs.hpp
- drivers/gfx/bochs/src/main.cpp
- drivers/gfx/plainfb/src/main.cpp
- drivers/gfx/virtio/src/main.cpp
- drivers/gfx/vmware/src/main.cpp
- protocols/fs/fs.bragi
These miscellaneous improvements came up while integrating lil.
> core/drm: general improvements

- drivers/libblockfs/src/ext2fs.cpp
Implement double indirect block allocation. This should be checked by someone because I am not completely sure that its correct and it could probably be improved in some ways.
> drivers/libblockfs: Implement ext2 double block allocation

- .github/workflows/fixups.yml
We already have this on mlibc, why not on managarm too. Bootstrap will receive the same treatment shortly.
> ci: add fixup checker

- servers/netserver/src/ip/tcp4.cpp
Implement sockname/peername and FIONREAD ioctl.
> Tcp additions

- kernel/thor/generic/thor-internal/futex.hpp
> thor: don't crash if sit disappears in FutexRealm::Node::cancel_()

- posix/subsystem/src/subsystem/usb/usb.cpp
Fix the minor version for USB 3.1.
> posix: Fix USB 3.1 minor version

- posix/init/src/stage1.cpp
This fixes at least Qt6 complaining about it.
> posix: Ensure /run is mode 0700

- core/include/core/tty.hpp
- drivers/usb/90-managarm-usb.rules
- drivers/usb/devices/serial/meson.build
- drivers/usb/devices/serial/src/controller.hpp
- drivers/usb/devices/serial/src/cp2102.cpp
- drivers/usb/devices/serial/src/cp2102.hpp
- drivers/usb/devices/serial/src/main.cpp
- drivers/usb/devices/serial/usb-serial.yml
- meson.build
- posix/subsystem/src/pts.cpp
- posix/subsystem/src/subsystem/generic.cpp
Depends on managarm/mlibc#932.
> CP2102 driver + termios fixes

- drivers/gfx/bochs/src/main.cpp
- kernel/thor/generic/hel.cpp
> Bochs VGA fixes

- core/drm/include/core/drm/core.hpp
- core/drm/src/ioctl.cpp
- drivers/gfx/bochs/src/bochs.hpp
- drivers/gfx/bochs/src/main.cpp
- drivers/gfx/plainfb/src/main.cpp
- drivers/gfx/plainfb/src/plainfb.hpp
- drivers/gfx/virtio/src/main.cpp
- drivers/gfx/virtio/src/virtio.hpp
- drivers/gfx/vmware/src/main.cpp
- drivers/gfx/vmware/src/vmware.hpp
> Expose gfx devices over mbus only after DRM setup completes

- posix/subsystem/src/requests.cpp
- protocols/posix/posix.bragi
> posix: Partially implement waitid

- posix/subsystem/src/nl-socket.cpp
- posix/subsystem/src/requests.cpp
- posix/subsystem/src/un-socket.cpp
- posix/subsystem/src/un-socket.hpp
Both for unix sockets and netlink sockets. Fixes dbus.
> posix: Support partial reads from sockets

- kernel/thor/arch/arm/debug.cpp
- kernel/thor/system/dtb/dtb.cpp
- kernel/thor/system/framebuffer/fb.cpp
- kernel/thor/system/pci/pci_discover.cpp
Bunch of miscellaneous fixes for aarch64 mostly lifted from @qookei's exynos branch.
> Misc aarch64 fixes

- posix/subsystem/src/requests.cpp
- protocols/posix/posix.bragi
Counterpart of managarm/mlibc#1036
> posix: Implement readlinkat

- posix/subsystem/src/fs.hpp
- posix/subsystem/src/inotify.cpp
- posix/subsystem/src/tmp_fs.cpp
In this PR I implement FIONREAD for inotify and add support for `IN_CREATE`.
> Some inotify fixes for SDDM

- posix/subsystem/src/epoll.cpp
- posix/subsystem/src/inotify.cpp
- posix/subsystem/src/nl-socket.cpp
- posix/subsystem/src/process.hpp
- posix/subsystem/src/procfs.cpp
- posix/subsystem/src/procfs.hpp
- posix/subsystem/src/requests.cpp
- posix/subsystem/src/signalfd.cpp
- posix/subsystem/src/timerfd.cpp
- posix/subsystem/src/vfs.cpp
Massive thanks to @48cf for the help!
Also brings some drive by fixes in error handling.
> posix: Implement `/proc/[pid]/fd`.

- posix/subsystem/src/subsystem/usb/usb.cpp
> posix: expose descriptors for USB 3.2 root hub

- posix/subsystem/src/eventfd.cpp
- posix/subsystem/src/eventfd.hpp
- posix/subsystem/src/requests.cpp
- protocols/posix/posix.bragi
Counterpart to managarm/mlibc#1046.
> posix: implement EFD_SEMAPHORE

- kernel/thor/system/acpi/ec.cpp
- kernel/thor/system/pci/pci_acpi.cpp
Depends on https://github.com/managarm/bootstrap-managarm/pull/331.
> Switch to new uACPI API

- drivers/gfx/plainfb/src/main.cpp
- drivers/usb/hcds/xhci/src/context.hpp
- drivers/usb/hcds/xhci/src/main.cpp
- kernel/thor/arch/x86/hpet.cpp
- kernel/thor/system/acpi/ec.cpp
- kernel/thor/system/acpi/madt.cpp
- kernel/thor/system/acpi/thor-internal/acpi/acpi.hpp
- kernel/thor/system/pci/pci_acpi.cpp
- posix/subsystem/src/pts.cpp
- posix/subsystem/src/subsystem/generic.cpp
Requires managarm/bootstrap-managarm#332.
> Misc. fixes

- kernel/thor/system/acpi/ec.cpp
We might get an SCI event at the same time as doing an embedded controller field access from AML.
> Guard EC access with a spinlock

- protocols/fs/fs.bragi
- servers/netserver/src/main.cpp
depends on https://github.com/managarm/managarm/pull/662
> Implement SIOCGIFBRDADDR/SIOCGIFHWADDR

- hel/meson.build
- kernel/eir/meson.build
- kernel/thor/meson.build
- meson.build
- meson_options.txt
- protocols/fs/meson.build
- protocols/hw/meson.build
- protocols/kernlet/meson.build
- protocols/mbus/meson.build
- protocols/ostrace/meson.build
- protocols/posix/meson.build
- protocols/svrctl/meson.build
- protocols/usb/meson.build
- testsuites/kernel-tests/meson.build
- testsuites/virt-test/meson.build
Depends on managarm/libarch#7, managarm/bragi#6.
> Fix sandboxing violations

- drivers/usb/90-managarm-usb.rules
- drivers/usb/devices/serial/meson.build
- drivers/usb/devices/serial/src/controller.hpp
- drivers/usb/devices/serial/src/cp2102/cp2102.cpp
- drivers/usb/devices/serial/src/cp2102/cp2102.hpp
- drivers/usb/devices/serial/src/ft232/ft232.cpp
- drivers/usb/devices/serial/src/ft232/ft232.hpp
- drivers/usb/devices/serial/src/main.cpp
- posix/subsystem/src/subsystem/usb/attributes.cpp
- posix/subsystem/src/subsystem/usb/attributes.hpp
- posix/subsystem/src/subsystem/usb/usb.cpp
- protocols/usb/src/api.cpp
The FTDI driver is tested with my FTDI FT232R and qemu's emulated FT232B (`-device usb-serial`).
> USB bugfixes and FTDI FT232 support

- core/include/core/netlink.hpp
- posix/subsystem/src/netlink/nl-socket.cpp
- posix/subsystem/src/netlink/nlctrl.cpp
- servers/netserver/src/netlink/queries.cpp
Continuing on from #681, fixes some comments on the PR.
> Address netlink comments

- servers/netserver/src/ip/ip4.cpp
- servers/netserver/src/ip/ip4.hpp
- servers/netserver/src/ip/tcp4.cpp
Test with `curl --interface <ifname> <url>`.
> netserver: implement TCP socket support for SO_BINDTODEVICE

- drivers/libblockfs/src/libblockfs.cpp
Found while trying to build `GNU Hello` and `zlib` inside Managarm
> Some self-hosting fixes

- docs/src/getting-started/supported/package-index.md
- docs/src/getting-started/trying-out.md
In preparation of multi-user support, document the default credentials needed.
> docs: Update the available packages section and add information on users

- drivers/kbd/src/main.cpp
While qemu seems to return the scancode number (e.g. 2) in the `get scancode` request (0xF0), VMWare seems to do what the osdev.org wiki documents. This implements a solution that supports both values.
Reference: https://wiki.osdev.org/PS/2_Keyboard#Commands
> drivers/kbd: correctly handle PS/2 reply in get scancode request

- drivers/libevbackend/src/libevbackend.cpp
- kernel/thor/system/acpi/pm-interface.cpp
- posix/subsystem/src/main.cpp
- posix/subsystem/src/requests.cpp
- posix/subsystem/src/requests.hpp
- protocols/hw/hw.bragi
- protocols/posix/posix.bragi
Supersedes #636 (I did an oopsie with git).
I fixed the comments on that PR and use the Hw protocol to accomplish the same.
Managarm counterpart of managarm/mlibc#1034
> Implement shutting down the system from userspace

- kernel/eir/arch/x86/arch.cpp
- kernel/eir/arch/x86/generic32_link.x
- kernel/eir/arch/x86/multiboot2/meson.build
- kernel/eir/arch/x86/multiboot2/multiboot2.S
- kernel/eir/arch/x86/multiboot2/multiboot2.cpp
- kernel/eir/generic/eir-internal/arch.hpp
- kernel/eir/generic/eir-internal/generic.hpp
- kernel/eir/generic/eir-internal/main.hpp
- kernel/eir/generic/elf_init.cpp
- kernel/eir/generic/main-function.cpp
- kernel/eir/generic/main.cpp
- kernel/eir/meson.build
- kernel/eir/protos/uefi/entry.cpp
- kernel/eir/protos/uefi/meson.build
This is a first step towards unifying different variants of Eir.
> Let x86_64 variants of Eir call into generic eirMain()

- kernel/common/riscv/csr.hpp
- kernel/eir/arch/riscv/arch.cpp
- kernel/eir/arch/riscv/cpu.cpp
- kernel/eir/arch/riscv/dtb.cpp
- kernel/eir/arch/riscv/meson.build
- kernel/eir/arch/riscv/paging.cpp
- kernel/eir/arch/riscv/platform/allwinner-d1/meson.build
- kernel/eir/arch/riscv/platform/virt/meson.build
- kernel/eir/arch/riscv/stubs.S
- kernel/eir/generic/eir-internal/main.hpp
- kernel/eir/generic/main.cpp
- kernel/eir/protos/limine/entry.cpp
- kernel/eir/protos/limine/limine.x
- kernel/eir/protos/limine/meson.build
- kernel/thor/arch/riscv/thor-internal/arch/paging.hpp
- tools/gen-initrd.py
This mostly just adds paging code and cleans up the build system in `kernel/eir` a bit.
> Implement missing pieces to let eir enter thor on RISC-V

- kernel/thor/arch/x86/debug.cpp
This is done after observing that it didn't work on VirtualBox without this.
> kernel/thor: set serial up to a known state

- .clang-format-include
- kernel/common/riscv/csr.hpp
- kernel/common/riscv/sbi.hpp
- kernel/eir/arch/riscv/cpu.cpp
- kernel/eir/arch/riscv/stubs.S
- kernel/eir/protos/limine/entry.cpp
- kernel/klibc/eir/interface.hpp
- kernel/thor/arch/riscv/cpu.cpp
- kernel/thor/arch/riscv/entry.S
- kernel/thor/arch/riscv/ints.cpp
- kernel/thor/arch/riscv/link.x
- kernel/thor/arch/riscv/meson.build
- kernel/thor/arch/riscv/paging.cpp
- kernel/thor/arch/riscv/stubs.cpp
- kernel/thor/arch/riscv/system.cpp
- kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp
- kernel/thor/arch/riscv/thor-internal/arch/ints.hpp
- kernel/thor/generic/main.cpp
- kernel/thor/generic/thor-internal/main.hpp
- kernel/thor/generic/thor-internal/ring-buffer.hpp
This makes thor boot. It gets to the init graph, but crashes with a page fault when trying to use the scheduler.
> kernel/thor: Implement functionality to get to init graph

- kernel/common/riscv/csr.hpp
- kernel/eir/arch/riscv/paging.cpp
- kernel/eir/arch/riscv/stubs.S
- kernel/thor/arch/riscv/cpu.cpp
- kernel/thor/arch/riscv/link.x
- kernel/thor/arch/riscv/meson.build
- kernel/thor/arch/riscv/paging.cpp
- kernel/thor/arch/riscv/stubs.S
- kernel/thor/arch/riscv/stubs.cpp
- kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp
- kernel/thor/arch/riscv/timer.cpp
This adds a proper exception handler that saves and restores state and various stubs to save and restore thread states.
> thor: Expand RISC-V functionality to get into kernel initialization fiber

- posix/subsystem/src/requests.cpp
> posix: handle AT_SYMLINK_NOFOLLOW for utimensat

- kernel/eir/protos/limine/entry.cpp
- kernel/thor/arch/riscv/cpu.cpp
- kernel/thor/arch/riscv/meson.build
- kernel/thor/arch/riscv/stubs.S
- kernel/thor/arch/riscv/stubs.cpp
- kernel/thor/arch/riscv/thor-internal/arch/cpu.hpp
- kernel/thor/arch/riscv/thor-internal/arch/trap.hpp
- kernel/thor/arch/riscv/trap.cpp
- kernel/thor/generic/thor-internal/address-space.hpp
This is the first step towards a working userspace; however, several other pieces (such as IRQs and handling IPIs in particular) are also required to make userspace work.
> thor: Handle ecalls from u-mode (= syscalls)

- kernel/eir/arch/arm/arch.cpp
- kernel/eir/arch/riscv/arch.cpp
- kernel/eir/arch/riscv/cpu.cpp
- kernel/eir/arch/riscv/eir-internal/arch/riscv.hpp
- kernel/eir/arch/riscv/paging.cpp
- kernel/eir/arch/x86/arch.cpp
- kernel/eir/generic/eir-internal/arch.hpp
- kernel/eir/generic/eir-internal/memory-layout.hpp
- kernel/eir/generic/main.cpp
- kernel/eir/generic/memory-layout.cpp
- kernel/klibc/eir/interface.hpp
- kernel/thor/arch/arm/thor-internal/arch/paging.hpp
- kernel/thor/arch/riscv/paging.cpp
- kernel/thor/arch/riscv/system.cpp
- kernel/thor/arch/riscv/thor-internal/arch/paging.hpp
- kernel/thor/arch/riscv/thor-internal/arch/system.hpp
- kernel/thor/arch/x86/thor-internal/arch/paging.hpp
- kernel/thor/generic/thor-internal/address-space.hpp
- kernel/thor/generic/thor-internal/arch-generic/paging.hpp
This adds support for 3 level paging on RISC-V.
> kernel: Support variable number of PT levels

- kernel/eir/arch/riscv/paging.cpp
- kernel/thor/arch/arm/ints.cpp
- kernel/thor/arch/arm/paging.cpp
- kernel/thor/arch/arm/thor-internal/arch/paging.hpp
- kernel/thor/arch/riscv/paging.cpp
- kernel/thor/arch/riscv/thor-internal/arch/paging.hpp
- kernel/thor/arch/riscv/trap.cpp
- kernel/thor/arch/x86/paging.cpp
- kernel/thor/arch/x86/thor-internal/arch/paging.hpp
- kernel/thor/generic/thor-internal/address-space.hpp
- kernel/thor/generic/thor-internal/arch-generic/cursor.hpp
- kernel/thor/generic/thor-internal/arch-generic/paging.hpp
This is required on most current RISC-V SoCs.
> kernel/thor: Support software access/dirty bits on RISC-V (Svade)

- kernel/thor/system/acpi/acpi.cpp
- kernel/thor/system/acpi/battery.cpp
- kernel/thor/system/acpi/ec.cpp
- kernel/thor/system/acpi/glue.cpp
- kernel/thor/system/acpi/madt.cpp
- kernel/thor/system/acpi/ps2.cpp
- kernel/thor/system/acpi/thor-internal/acpi/helpers.hpp
- kernel/thor/system/pci/pci_acpi.cpp
Depends on managarm/bootstrap-managarm#420
> thor: Update uACPI users for latest uACPI commits

- kernel/common/dtb.hpp
- kernel/thor/arch/riscv/cpu.cpp
- kernel/thor/arch/riscv/meson.build
- kernel/thor/arch/riscv/plic.cpp
- kernel/thor/arch/riscv/thor-internal/arch/ints.hpp
- kernel/thor/arch/riscv/thor-internal/arch/system.hpp
- kernel/thor/arch/riscv/trap.cpp
- kernel/thor/generic/thor-internal/cpu-data.hpp
- kernel/thor/system/dtb/dtb.cpp
- kernel/thor/system/dtb/thor-internal/dtb/dtb.hpp
- kernel/thor/system/dtb/thor-internal/dtb/irq.hpp
- kernel/thor/system/pci/pci_dtb.cpp
This PR also generalizes the parsing of interrupt-related DT properties.
> thor: Support external IRQs via PLIC on RISC-V

- kernel/thor/system/pci/pci_discover.cpp
This PR fixes two issues that were exposed by running on RISC-V:
- We need to defer MSI enablement until BAR allocation is done (in particular, it is necessary to access a BAR to set up MSI-X).
- EDK2/OVMF on RISC-V seems to properly allocate BARs; however, it does not properly enable decoding of memory and PIO BARs. Hence, this PR changes our code to always overwrite the decoding bits in the PCI command register, even if the BAR allocation is taken from the firmware.
> thor: Fix MSI enablement and ensure PIO / memory decoding is enabled for PCI

- posix/init/src/stage1.cpp
This PR refactors the existing uevent-based logic to find the root fs in such a way that it can be used to also discover devices other than block devices.
> posix: Generalize uevent code in init stage1

- drivers/nic/virtio/include/nic/virtio/virtio.hpp
- drivers/nic/virtio/src/virtio.cpp
- kernel/eir/protos/uefi/efi.hpp
- posix/subsystem/src/drvcore.cpp
- posix/subsystem/src/drvcore.hpp
- posix/subsystem/src/subsystem/acpi.cpp
- posix/subsystem/src/subsystem/block.cpp
- posix/subsystem/src/subsystem/drm.cpp
- posix/subsystem/src/subsystem/pci.cpp
- posix/subsystem/src/subsystem/pci.hpp
- posix/subsystem/src/subsystem/usb/usb.cpp
- protocols/fs/include/protocols/fs/client.hpp
- protocols/fs/src/client.cpp
- servers/netserver/src/ip/tcp4.cpp
- servers/netserver/src/main.cpp
Various fixes in preparation for NVMe-oF.
> NVMe-over-fabrics support, part 2

- drivers/libblockfs/include/blockfs.hpp
- drivers/libblockfs/src/ext2fs.cpp
- drivers/libblockfs/src/libblockfs.cpp
- kernel/thor/generic/hel.cpp
- kernel/thor/generic/main.cpp
- kernel/thor/generic/ostrace.cpp
- kernel/thor/generic/thor-internal/main.hpp
- kernel/thor/generic/thor-internal/ostrace.hpp
- posix/subsystem/meson.build
- posix/subsystem/src/main.cpp
- posix/subsystem/src/observations.cpp
- posix/subsystem/src/ostrace.cpp
- posix/subsystem/src/ostrace.hpp
- posix/subsystem/src/requests.cpp
- protocols/ostrace/include/protocols/ostrace/ostrace.hpp
- protocols/ostrace/ostrace.bragi
- protocols/ostrace/src/ostrace.cpp
- tools/ostrace/extract-ostrace.cpp
Improve ostrace to make it easier to use. See the commit message and code comments for details.
> ostrace: Improve infrastructure

- kernel/thor/system/acpi/glue.cpp
Depends on managarm/bootstrap-managarm#427
> thor: Update uACPI glue code for new uACPI version

- kernel/thor/arch/riscv/aplic.cpp
- kernel/thor/arch/riscv/meson.build
- kernel/thor/arch/riscv/plic.cpp
- kernel/thor/arch/riscv/thor-internal/arch/ints.hpp
- kernel/thor/arch/riscv/thor-internal/arch/trap.hpp
- kernel/thor/arch/riscv/trap.cpp
This adds support for handling external interrupts using the APLIC.
Note that this does not yet work in Qemu due to https://gitlab.com/qemu-project/qemu/-/issues/2763.
> thor: Support APLIC on RISC-V

- kernel/thor/arch/arm/smp.cpp
- kernel/thor/arch/riscv/smp.cpp
- kernel/thor/arch/x86/cpu.cpp
- kernel/thor/arch/x86/pic.cpp
- kernel/thor/generic/hel.cpp
- kernel/thor/generic/load-balancing.cpp
- kernel/thor/generic/main.cpp
- kernel/thor/generic/servers.cpp
- kernel/thor/generic/thor-internal/load-balancing.hpp
- kernel/thor/generic/thor-internal/thread.hpp
- kernel/thor/generic/thread.cpp
- kernel/thor/meson.build
Thor already had code to migrate threads from one CPU to another but it did not migrate automatically. Add an algorithm that tries to balance the load periodically.
> thor: Add load balancing

- posix/subsystem/src/procfs.cpp
- posix/subsystem/src/procfs.hpp
- posix/subsystem/src/pts.cpp
- posix/subsystem/src/requests.cpp
- posix/subsystem/src/sysfs.cpp
- posix/subsystem/src/tmp_fs.cpp
- posix/subsystem/src/un-socket.cpp
- posix/subsystem/src/un-socket.hpp
- protocols/fs/src/server.cpp
sorry for the undescriptive title but that's what it is
> Various POSIX improvements

- protocols/fs/include/protocols/fs/common.hpp
- servers/netserver/meson.build
- servers/netserver/src/ip/icmp.cpp
- servers/netserver/src/ip/icmp.hpp
- servers/netserver/src/ip/ip4.cpp
- servers/netserver/src/ip/ip4.hpp
- servers/netserver/src/ip/udp4.cpp
- servers/netserver/src/main.cpp
- servers/netserver/src/raw.cpp
> netserver ICMP sockets

- kernel/thor/arch/x86/pic.cpp
- kernel/thor/generic/ostrace.cpp
- kernel/thor/generic/schedule.cpp
- kernel/thor/generic/thor-internal/cpu-data.hpp
- kernel/thor/generic/thor-internal/ostrace.hpp
This enables ostrace event emission from the kernel.
> thor: Support in-kernel ostrace events

- kernel/thor/arch/arm/timer.cpp
- kernel/thor/arch/riscv/timer.cpp
- kernel/thor/arch/x86/hpet.cpp
- kernel/thor/arch/x86/pic.cpp
- kernel/thor/arch/x86/rtc.cpp
- kernel/thor/arch/x86/thor-internal/arch/pic.hpp
- kernel/thor/generic/hel.cpp
- kernel/thor/generic/irq.cpp
- kernel/thor/generic/kernel-log.cpp
- kernel/thor/generic/load-balancing.cpp
- kernel/thor/generic/schedule.cpp
- kernel/thor/generic/thor-internal/arch-generic/timer.hpp
- kernel/thor/generic/thor-internal/cpu-data.hpp
- kernel/thor/generic/thor-internal/timer.hpp
- kernel/thor/generic/thread.cpp
- kernel/thor/generic/timer.cpp
- kernel/thor/system/acpi/glue.cpp
This should improve scalability by giving each CPU its own timer data structure.
> thor: Make PrecisionTimerEngine per-CPU

- kernel/thor/arch/arm/gic_v2.cpp
- kernel/thor/arch/arm/gic_v3.cpp
- kernel/thor/arch/arm/ints.cpp
- kernel/thor/arch/arm/smp.cpp
- kernel/thor/arch/arm/thor-internal/arch/gic.hpp
- kernel/thor/arch/arm/thor-internal/arch/gic_v2.hpp
- kernel/thor/arch/arm/thor-internal/arch/system.hpp
- kernel/thor/arch/arm/timer.cpp
- kernel/thor/system/dtb/dtb.cpp
- kernel/thor/system/dtb/dtb_discover.cpp
- kernel/thor/system/dtb/thor-internal/dtb/dtb.hpp
- kernel/thor/system/pci/pci_dtb.cpp
Fix PPI IrqPins being shared between CPUs, and remove ARM-specific code from the core DTB code.
> AArch64 and DTB fixes and cleanup

- posix/subsystem/src/netlink/nl-socket.cpp
- posix/subsystem/src/netlink/nl-socket.hpp
> posix: Fix a netlink send to closed socket bug

- posix/subsystem/src/un-socket.cpp
> Various fixes for unix sockets

- kernel/thor/system/acpi/glue.cpp
Depends on managarm/bootstrap-managarm#445.
> thor: implement kernel API changes for uACPI 1.0.1

- posix/subsystem/meson.build
- posix/subsystem/src/cgroupfs.cpp
- posix/subsystem/src/cgroupfs.hpp
- posix/subsystem/src/drvcore.cpp
- posix/subsystem/src/file.hpp
- posix/subsystem/src/fs.cpp
- posix/subsystem/src/requests.cpp
- posix/subsystem/src/timerfd.cpp
- protocols/posix/posix.bragi
Various fixes here and there, working towards systemd init.
> Systemd init part1

- posix/subsystem/src/procfs.cpp
- posix/subsystem/src/procfs.hpp
> posix: Add /proc/sys/kernel/random/boot_id

- posix/subsystem/src/process.cpp
- posix/subsystem/src/process.hpp
- posix/subsystem/src/requests.cpp
- protocols/posix/posix.bragi
Should be merged with managarm/mlibc#1247
> posix: Groundwork to allow F_DUPFD to be properly implemented

- posix/subsystem/src/file.cpp
This PR adds an auto launch of elogind if it's installed, and adds some required items (mostly workarounds) on the Managarm side. As a bonus, logging was improved for not implemented file operations.
> posix: Improve logging on unimplemented file operations

- posix/init/src/stage2.cpp
Depends on managarm/bootstrap-managarm#436.
> posix/init: switch to systemd udev

- kernel/thor/arch/x86/ept.cpp
- kernel/thor/arch/x86/npt.cpp
- kernel/thor/arch/x86/thor-internal/arch/paging.hpp
This was probably just a typo.
> thor: Fix missing 0 in pteAddress

- posix/subsystem/src/observations.cpp
- posix/subsystem/src/un-socket.cpp
- protocols/fs/src/server.cpp
This PR adds the final touches to an initial boot with systemd.
> Systemd init part3

- drivers/usb/runsvr-usbhid.service
Must be merged in sync with managarm/bootstrap-managarm#447
> drivers/usb: Add an unit file to launch input-usbhid from systemd

- core/include/core/clock.hpp
- core/lib/clock.cpp
- posix/subsystem/src/requests.cpp
- posix/subsystem/src/timerfd.cpp
- posix/subsystem/src/timerfd.hpp
- protocols/posix/posix.bragi
Also replace the legacy requests by modern ones.
> posix: Improve timerfd (bugfix, absolute time support, CLOCK_REALTIME)

- drivers/usb/devices/hid/src/main.cpp
> drivers/hid: report capslock keypresses

- kernel/thor/generic/gdbserver.cpp
This ensures that (remote) gdb automatically loads the correct binaries from the sysroot.
> thor: report absolute paths for servers over gdbserver

- core/include/core/logging.hpp
- kernel/thor/generic/servers.cpp
- protocols/svrctl/include/protocols/svrctl/server.hpp
- protocols/svrctl/meson.build
- protocols/svrctl/src/server.cpp
- protocols/svrctl/svrctl.bragi
- utils/runsvr/src/main.cpp
Needed in order to build with managarm/bragi#9 merged
> protocols/svrctl: Split into separate requests

- posix/subsystem/src/drvcore.cpp
- posix/subsystem/src/drvcore.hpp
This correctly places devices in sysfs, so that e.g. card0 shows up under `/sys/devices/pci0000:00/0000:00:02.0/drm/card0`, unlike the previous incorrect `/sys/devices/pci0000:00/0000:00:02.0/card0` (notice the missing drm directory). This fixes some libdrm functions that previously just returned errors.
> posix: correctly organize class devices in sysfs

- posix/subsystem/src/drvcore.cpp
- posix/subsystem/src/drvcore.hpp
Reverts managarm/managarm#947 until review comments have been fixed.
> Revert "posix: correctly organize class devices in sysfs"

- drivers/nic/rtl8168/src/hw-config.cpp
This adds support for the RTL8168evl chipset. Seems to me to be very similar to MacVer35, but with slightly differently ordered init logic. I have not tested whether this order matters, but given that it has its own init function in the linux driver, I assume it likely does.
This works well enough to obtain a DHCP lease on my network and receive UDP broadcast packets.
> drivers/rtl8168: add support for MacVer34

- posix/subsystem/src/extern_fs.cpp
- posix/subsystem/src/file.cpp
- posix/subsystem/src/pts.cpp
- protocols/fs/include/protocols/fs/client.hpp
- protocols/fs/src/client.cpp
- protocols/fs/src/server.cpp
These were needed for getting logind working.
> posix: `seek` improvements

- core/virtio/meson.build
- hel/meson.build
- kernel/thor/meson.build
- mbus/meson.build
- meson.build
- protocols/fs/meson.build
- protocols/svrctl/meson.build
- protocols/usb/meson.build
Depends on managarm/bootstrap-managarm#515.
> build: use pkgconfig over symlinked subprojects for libasync/libsmarter

- kernel/thor/arch/x86/vt_d.cpp
- kernel/thor/generic/hel.cpp
- kernel/thor/system/acpi/madt.cpp
Some bugfixes here and there with kasan and ubsan enabled.
> Kasan ubsan hunting

- kernel/eir/arch/arm/arch.cpp
- kernel/eir/arch/arm/platform/raspi4/raspi4.cpp
- kernel/thor/arch/arm/gic_v2.cpp
- kernel/thor/arch/arm/smp.cpp
- kernel/thor/arch/arm/thor-internal/arch/paging.hpp
- kernel/thor/arch/riscv/thor-internal/arch/paging.hpp
- kernel/thor/arch/x86/ept.cpp
- kernel/thor/arch/x86/npt.cpp
- kernel/thor/arch/x86/thor-internal/arch/paging.hpp
- kernel/thor/generic/thor-internal/arch-generic/cursor.hpp
- kernel/thor/system/dtb/thor-internal/dtb/dtb.hpp
- kernel/thor/system/pci/pci_discover.cpp
> Even more Raspberry Pi 4 and ARM fixes.

- kernel/common/physical-buddy.hpp
The code previously used to restrict allocations to the given amount of physical address bits could wrongfully descend into fully allocated chunks.
> kernel: Fix bug in buddy allocator address size restriction

- posix/subsystem/src/procfs.cpp
- posix/subsystem/src/procfs.hpp
Also replaces raw pointers with weak pointers in the node structs
> posix: Implement procfs LinkNode::getStats

- kernel/thor/system/dtb/dtb_discover.cpp
- posix/subsystem/meson.build
- posix/subsystem/src/firmware/dt.cpp
- posix/subsystem/src/firmware/dt.hpp
- posix/subsystem/src/main.cpp
- protocols/hw/hw.bragi
- protocols/hw/include/protocols/hw/client.hpp
- protocols/hw/src/client.cpp
Expose dt nodes in /sys/firmware/devicetree/base.
> Expose dt nodes via sysfs

- kernel/eir/boot/uefi/entry.cpp
- kernel/eir/boot/uefi/pe.hpp
Part of #1040 (but does not support loading the command line yet).
> eir: Support loading initrd from UKI
